### PR TITLE
Roll back of beforeEach tests

### PR DESCRIPTION
**Pull request by nsthorat**
For some reason this breaks unit tests. I spent about 2 hours investigating but could not figure out why it was breaking: https://github.com/tensorflow/tfjs/issues/162

Will wait for @dsmilkov to come back from vacation to help debug backend swapping in unit tests.

This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/936)

### CODE REVIEW

**Comment by caisq** [comment]
:lgtm_strong:

Thanks for debugging this issue! I'm curious to learn why this seems to affect some machines, but not others.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/936#-:-L9gxHjcCZSI7QKDh9Bo:b-a5gosh)*

**Comment by QuantumInformation** [comment]
Perhaps the state MathBackendWebGL is messing up the next test, vs new is giving a clean state.

**Comment by QuantumInformation** [comment]
Jasmine core is now at version 3 btw

**Comment by nsthorat** [comment]
It's possible, but that shouldn't be happening. When a regular page loads we have a single backend instance. It also seems particular to our custom setup function of slice4d.

**Pull request merged**
