### PR TITLE
Add tf.signal.frame() op.

### PR DESCRIPTION
**Pull request by Lewuathe**
Add frame op as provided in [TensorFlow core](https://www.tensorflow.org/api_docs/python/tf/signal/frame). It's also needed to implement stft, istft ops to make slices of the sample.

See: https://github.com/tensorflow/tfjs/issues/1362

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1713)

### CODE REVIEW

**Comment by nsthorat** [comment]
See this for failures: https://pantheon.corp.google.com/cloud-build/builds/ecf44c74-fa85-4c83-ae90-7f42c9d0c603?project=learnjs-174218

**Comment by Lewuathe** [comment]
> See this for failures: https://pantheon.corp.google.com/cloud-build/builds/ecf44c74-fa85-4c83-ae90-7f42c9d0c603?project=learnjs-174218

Thanks but unfortunately I do not have permission to look into that. But anyway, I guess the problem is fixed.

**Comment by nsthorat** [comment]
Ah apologies that's the internal version of the link, you can see the failure by clicking details:

image

**Comment by nsthorat** [comment]
Ah looks like we may have a bug, I think this will fix it: https://github.com/tensorflow/tfjs-core/pull/1737

**Comment by nsthorat** [comment]
Thanks for the awesome PR as always @Lewuathe :)

**Pull request merged**
