### PR TITLE
Add fft ops

### PR DESCRIPTION
**Pull request by Lewuathe**
#### Description

FEATURE

Add fft ops. Since TypeScript/JavaScript does not support complex number natively, it regards two length array as a complex number so that it can support [n, 2] shape tensor as input.

```
const real = tf.tensor1d([1, 2, 3]);
const imag = tf.tensor1d([1, 2, 3]);
const input = tf.complex(real, imag);
tf.fft(input); // => [[6, 6], [-2.3660252, -0.63397473], [-0.6339747, -2.3660254]]
```

see: https://github.com/tensorflow/tfjs/issues/214

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1191)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Adding @caisq and @pyu10055 for review since they have experience using FFT.

**Comment by nsthorat** [comment]
I'm going to add a complex64 dtype. Here is the issue outlining the proposal: https://github.com/tensorflow/tfjs/issues/565

**Comment by Lewuathe** [comment]
@caisq Thank you for the tailored review! I updated what I can for now.

Some other things should wait for the design of [complex64](https://github.com/tensorflow/tfjs/issues/565). Unless defining the design of `complex64`, it would be difficult to align the interface of fft with TensorFlow core.

**Comment by nsthorat** [comment]
Okay so the complex64 dtype change was merged! Let me know if you have any questions about how it works, it should be pretty straightforward to migrate. In each of the backends, complex tensors now have a "real" and "imag" backing tensor.

**Comment by Lewuathe** [comment]
@nsthorat Thank you! I'll take a look and try to migrate to use compex64 dtype in fft ops.

**Comment by Lewuathe** [comment]
@nsthorat I updated fft to use complex64 type tensor as input/output. Could you take a look when you get a chance?

**Comment by Lewuathe** [comment]
Yes, I'm still doing post review followup.

**Comment by nsthorat** [comment]
@Lewuathe send me a ping when you're ready for me to look.

**Comment by Lewuathe** [comment]
@nsthorat Test has passed. Could you take a look again?

**Comment by nsthorat** [comment]
Let me know when this is ready to look at again.

**Comment by Lewuathe** [comment]
Yeah, It’s ready. Please take a look.

**Comment by masseyl** [comment]
I know I'm not part of this review, but great work - thanks!

**Pull request merged**
