### PR TITLE
Add BrowserHTTPRequest.load()

### PR DESCRIPTION
**Pull request by caisq**
Previously BrowserHTTPRequest only had the save() method. This PR
completes the IOHandler implementation. After this PR is merged
and a new release is put out for tfjs-core, tfjs-layer will be able
to utilize BrowserhTTPRequest.load() for HTTP-based loading.

BrowserHTTPRequest.load() supports requestInit (HTTP request options).

Towards: https://github.com/tensorflow/tfjs/issues/290

FEATURE Add `load()` support to `tf.io.browserHTTPRequest()`.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1067)

### CODE REVIEW

**Comment by caisq** [comment]
cc @jameswex

**Comment by dsmilkov** [comment]
:lgtm_strong: Nice work Shanqing. Couple smallish suggestions

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/io/browser_http.ts, line 109 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1067#-LDrVcFc2JDjsd0ULfXy:-LDrVcFc2JDjsd0ULfXz:b-um4q1j) ([raw file](https://github.com/tensorflow/tfjs-core/blob/2333dd072868fa994879098ae7a22878776cd3a7/src/io/browser_http.ts#L109)):*
> ```XML
>   }
> 
>   async load(): Promise<ModelArtifacts> {
> ```

since this is user-facing, would be great to explain what it does in a jsdoc

---

*[src/io/browser_http.ts, line 111 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1067#-LDrUjSHAWx-Pn1Qbzdc:-LDrUjSHAWx-Pn1Qbzdd:bu7gyxo) ([raw file](https://github.com/tensorflow/tfjs-core/blob/2333dd072868fa994879098ae7a22878776cd3a7/src/io/browser_http.ts#L111)):*
> ```XML
>   async load(): Promise<ModelArtifacts> {
>     const modelConfigRequest = await fetch(this.path, this.requestInit);
>     const modelConfig = await modelConfigRequest.json();
> ```

after this line might be a good place to do same input validation (make sure that modelTopology exists as a key, etc)

---

*[src/io/weights_loader.ts, line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1067#-LDrVP-OEHgG7Ne0PDOd:-LDrVP-P9fLipsfixUhe:b2jd5ts) ([raw file](https://github.com/tensorflow/tfjs-core/blob/2333dd072868fa994879098ae7a22878776cd3a7/src/io/weights_loader.ts#L33)):*
> ```XML
>  *   length as `fetchURLs`.
>  */
> export async function loadWeightsAsArrayBuffer(
> ```

just double checking: this is exposed to the end users right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1067#-:-LDrVmCPAb_-ig7afxZk:b-xfm4am)*

**Comment by caisq** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/io/browser_http.ts, line 111 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1067#-LDrUjSHAWx-Pn1Qbzdc:-LDrs6Uz5mZwAHJwidYT:bgwzc7i) ([raw file](https://github.com/tensorflow/tfjs-core/blob/4dbcc5d5a15a341c24bfba0c22e48fc40fc55cad/src/io/browser_http.ts#L111)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

after this line might be a good place to do same input validation (make sure that modelTopology exists as a key, etc)
</blockquote></details>

This is actually done implicitly on line 116, which checks to see if there is a weightManifest and takes action accordingly. Also, please note that this load() implementation is written in a way to allow the model JSON to contain weights only or topology only. But I realized that we shouldn't allow *both* weights and topology to be missing. Added a check here. Also added a unit test.

---

*[src/io/weights_loader.ts, line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1067#-LDrVP-OEHgG7Ne0PDOd:-LDrptZ334zZ-S_nkH-b:b-y879ab) ([raw file](https://github.com/tensorflow/tfjs-core/blob/4dbcc5d5a15a341c24bfba0c22e48fc40fc55cad/src/io/weights_loader.ts#L33)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

just double checking: this is exposed to the end users right?
</blockquote></details>

This is *not* exposed in the public API of tfjs-core. This is just for other modules in tfjs-core to use.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1067)*

**Comment by meme** [comment]
This pull request breaks support in tfjs-node, which requires this module to operate, the offending lines are here:
https://github.com/tensorflow/tfjs-core/pull/1067/files#diff-de1c2d9883e723bf8179aa7e45957a61R118 and here,
https://github.com/tensorflow/tfjs-core/pull/1067/files#diff-5c8893bf31b1cd319675fcf3524961e8R36

I recommend that these are replaced with Node's file system utilities so that loading models from disk can be supported. I am willing to work on this if needed.

**Pull request merged**
