### PR TITLE
Implement AddSign and PowerSign Optimizers

### PR DESCRIPTION
**Pull request by principal-academy**
This is a GPU and CPU implementation of Quoc Le's optimizers for deep neural networks, dubbed AddSign and PowerSign. Per the specification with no decay per iteration, found at arXiv:1709.07417 [cs.AI]

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/260)

### CODE REVIEW

**Comment by principal-academy** [comment]
I signed it!

**Comment by principal-academy** [comment]
It seems the Travis CI for this project is currently missing binaries to test against Mac versions of Firefox and Chrome? Or it doesn't have permissions to access said binaries?

24 10 2017 14:40:55.151:ERROR [launcher]: Cannot load browser "bs_firefox_mac"!
 Error: Username is required.

24 10 2017 14:40:55.152:ERROR [launcher]: Cannot load browser "bs_chrome_mac"!
 Error: Can not resolve circular dependency! (Resolving: browserStackClient -> browserStackClient)

**Comment by principal-academy** [comment]
I signed it!

**Comment by dsmilkov** [comment]
Thanks! See https://github.com/PAIR-code/deeplearnjs/pull/263#issuecomment-339708392 for details about the BrowserStack testing. tl;dl; We are turning off BrowserStack testing for external PRs for now and we'll keep looking for a better solution.

**Comment by dsmilkov** [comment]
Thanks for apologies for the delayed review. Generally looks great! Left a few comments. Feel free to reply after addressing the comments - I'll rereview and merge. Thank you for your contribution!

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[src/graph/optimizers/addsign_optimizer.ts, line 3 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/260#-KxntZ5lQf8KRkZDVpG1:-KxntZ5lQf8KRkZDVpG2:bh5zv48) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a295b6d4e2472102126b6a8ba5daecef160433ed/src/graph/optimizers/addsign_optimizer.ts#L3)):*
> Principal Academy Inc

Please change this to Google Inc. Unfortunately, we can't accept a PR with a modified license.

You can still add your name as a contributor below the license, in a separate comment. Something like:

`// Contributed by Principal Academy (https://github.com/principal-academy)`

---

*[src/math/math.ts, line 1244 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/260#-KxUaUVWKR5_LcV1cwWj:-KxUaUVWKR5_LcV1cwWk:b-rogkf0) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a295b6d4e2472102126b6a8ba5daecef160433ed/src/math/math.ts#L1244)):*
> ```XML
> 
>   /**
>    * Computes sign of the input NDArray element-wise, y = 1 if x >= 0 | -1 if x 
> ```

adjust the jsdoc to reflect the fact that `sign(0) == 0`

---

*[src/math/unaryop_test.ts, line 209 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/260#-KxUaDhygJGyn8coe9WT:-KxUaDhzZp0kwIfvKkeg:b-fm04rh) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a295b6d4e2472102126b6a8ba5daecef160433ed/src/math/unaryop_test.ts#L209)):*
> , -1, 1, -1, 1, -1

ajust test here and elsewhere to make sure `sign(0) == 0`

---

*[src/math/webgl/unaryop_gpu.ts, line 73 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/260#-KxUZnP4lyQYzBiFj-gq:-KxUZnP4lyQYzBiFj-gr:bm56w5w) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a295b6d4e2472102126b6a8ba5daecef160433ed/src/math/webgl/unaryop_gpu.ts#L73)):*
> (x == x) ? (x == 0.0 ? 1.0 : sign(x)) : x;

We want to stay compatible with tensorflow [tf.sign](https://www.tensorflow.org/api_docs/python/tf/sign)

which means it should return
0, if x == 0;
1, if x > 0;
-1, if x < 0;
NaN, if x is NaN; (TF doesn't do this, but we want deeplearnjs to propage NaNs)

luckily GLSL [sign()](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/sign.xhtml) handles the first 3 cases so I think the shader can be simplified to `return (x == x) ? sign(x) : x;`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/260#-:-KxnuigNVX6CZb1G42FE:bzige42)*

**Comment by principal-academy** [comment]
Thanks for the review @dsmilkov !

I've affected the required changes and repushed. Please let me know if ready to merge.

**Comment by dsmilkov** [comment]
:lgtm_strong: Nice work! This is all good! Sorry for the long delay! You will have to sync and resolve some merge conflicts since we changed internals of math. Let me know when that is done, and I'll merge. Thank you!

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/260#-:-L0ltUsJruGdOQk3prPS:bzhrahm)*

**Comment by dsmilkov** [comment]
Hi,

First, a big thank you for your contribution. We will be closing this PR since it is using Graph mode which we removed with 0.6.0. Also, we are trying to stay aligned with the official TensorFlow API (non-contrib API), which doesn't have these optimizers.

**Pull request closed without merging**
