### PR TITLE
Optimizers: Change epsilon value as per environment

### PR DESCRIPTION
**Pull request by ManrajGrover**
#### Description
This PR changes epsilon value as per environment for optimizers. Not sure if this will introduce any inconsistencies in different environments.

Attempts to fix: https://github.com/tensorflow/tfjs/issues/425.

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1106)

### CODE REVIEW

**Comment by nsthorat** [comment]
Can you also update this test here to make sure it passes on browerstack?

https://github.com/tensorflow/tfjs-core/blob/master/src/optimizers/adadelta_optimizer_test.ts#L24

You should use "ALL_ENVS" for the environment -- if your change works it will pass on iOS!

---

Review status: 0 of 1 LGTMs obtained

---

*[src/optimizers/adadelta_optimizer.ts, line 29 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1106#-LFIQl_G-Y1ZP_k4p2sH:-LFIQl_G-Y1ZP_k4p2sI:b-p8yq8n) ([raw file](https://github.com/tensorflow/tfjs-core/blob/58eaaabf34eda1d7dba3f1fb5f8dfeb8eac3255c/src/optimizers/adadelta_optimizer.ts#L29)):*
> ```XML
> import * as optimizer_utils from './optimizer_utils';
> 
> const DEFAULT_EPSILON = optimizer_utils.getOptimizerDefaultEpsilonValue();
> ```

Unfortunately this isn't going to work in unit tests, when the page loads this value will be computed immediately, and the unit tests will not be able to override the environment to get a new epsilon.

You should call this method inside the constructor of the optimizer so we can check the environment flags lazily.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1106#-:-LFIRPS5-BFyJwhamxYu:b8n6c8)*

**Comment by nsthorat** [comment]
Can you use null instead of undefined for defaults? Then LGTM

**Comment by ManrajGrover** [comment]
@nsthorat Yup, fixed it. Had to change default epsilon value to `1e-4` for the tests to pass. Should be good to go now.

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1106#-:-LFIyZtz3AEmRkmSDo67:b-jbsf8z)*

**Comment by nsthorat** [comment]
Thanks Manraj!

**Pull request merged**
