### PR TITLE
added tf.where gradient function and associated tests

### PR DESCRIPTION
**Pull request by julianoks**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1059)

### CODE REVIEW

**Comment by julianoks** [comment]
I signed it!

**Comment by nsthorat** [comment]
Looks really good! Couple comments inline.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[src/ops/logical_ops.ts, line 165 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/1059#-LEFPQOVD137yEcHr8D3:-LEFPQOW76Xqel9AYSmF:be02b5o) ([raw file](https://github.com/tensorflow/tfjs-core/blob/d2f898a60a0dfd510dd4f9a01b2264d8c4349fbd/src/ops/logical_ops.ts#L165)):*
> ```XML
>     }
> 
>     const customOp = customGrad((condition, a, b) => {
> ```

Instead of using customGrad, you can pass the grad function to "runKernel", like we do for the other ops. Can you make that change?

---

*[src/ops/logicalop_test.ts, line 563 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/1059#-LEFPn24197QKmXvb6nV:-LEFPn24197QKmXvb6nW:b-mnsg4e) ([raw file](https://github.com/tensorflow/tfjs-core/blob/d2f898a60a0dfd510dd4f9a01b2264d8c4349fbd/src/ops/logicalop_test.ts#L563)):*
> ```XML
>   });
> 
>   it('1D gradient', () => {
> ```

in these unit tests, can you also define a dy?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1059#-:-LEFPp4l1uBibe9ub6gA:b3xho7d)*

**Comment by julianoks** [comment]
@nsthorat I've implemented the changes!

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1059#-:-LEyeLIp7h7r2ZG4gzlv:b-jbsf8z)*

**Comment by nsthorat** [comment]
Thank you!

**Pull request merged**
