### PR TITLE
Test Windows and MacOS for tfjs-core.

### PR DESCRIPTION
**Pull request by nkreeger**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1491)

### CODE REVIEW

**Comment by nsthorat** [comment]
Looking back at this -- I wonder if this is the right place to do this testing. tfjs-core is mostly browser unit testing. This would greatly increase the size of every travis run, I wonder if we could do this in the tfjs-node package instead so we don't bloat this?

**Comment by dsmilkov** [comment]
+1 we won't get much benefit from calling `yarn/yarn test-node` in windows here. We will get much more benefit from running browserstack on Windows (to test our shaders on D3D via Angle), but that doesn't require a new travis OS (travis linux is sufficient for that)

I think tfjs-node would be the best place for this.

**Comment by nsthorat** [comment]
Apologies, closed the wrong PR :)

**Comment by nsthorat** [comment]
But I do think this should be closed anyways haha, let us know your thoughts :)

**Comment by nsthorat** [comment]
Closing this out since we're doing this with cloud CI now.

**Pull request closed without merging**
