### PR TITLE
Adds ability to load quantized weights by de-quantizing them.

### PR DESCRIPTION
**Pull request by adarob**
Works in conjunction with https://github.com/tensorflow/tfjs-converter/pull/87.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/965)

### CODE REVIEW

**Comment by nsthorat** [comment]
Thanks for doing this!

Can you go talk to Suharsh and make sure this approach seems reasonable to him? Specifically I want to make sure 0s are 0s (which means you may have to use scale / offset).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/weights_loader.ts, line 128 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/965#-LAPRCzO66-puBZduxqv:-LAPRCzO66-puBZduxqw:b-fgcxfk) ([raw file](https://github.com/tensorflow/tfjs-core/blob/ec2a93ade53cd60eb207a293d0fcf9ee2d8036d4/src/weights_loader.ts#L128)):*
> ```XML
>       const fetchUrl = filePathPrefix +
>           (!filePathPrefix.endsWith('/') ? '/' : '') + filepath;
>       requests.push(fetch(fetchUrl, requestOptions));
> ```

this should not be removed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/965#-:-LAPRsAg82nRtku_5BX3:byndapr)*

**Comment by adarob** [comment]
@nsthorat @pyu10055 this is now ready for review.

**Comment by dsmilkov** [comment]
Looks great! One comment to reduce number of intermediate allocated arrays, and after that I'm very happy to get this in!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/weights_loader.ts, line 178 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/965#-LAt5ZOk3dhg_Yn5HzLj:-LAt5ZOk3dhg_Yn5HzLk:b-a81vea) ([raw file](https://github.com/tensorflow/tfjs-core/blob/37a204a847865de96ac91ef08356d8fac8fb132c/src/weights_loader.ts#L178)):*
> ```XML
>         let quantizedArray: Float32Array;
>         if (quantization.dtype === 'uint8') {
>           quantizedArray = Float32Array.from(new Uint8Array(byteBuffer));
> ```

no need to have this intermediate Float32Array. Just allocate the final `typedArray `depending on the logical dtype (Int32Array or Float32Array). JS will give you all zeros if you use the c-tor with the size passed in.

Then iterate directly over the UIn8Array or UInt16Array (depending on the quantized dtype), and do the math directly there.

```ts
const quantized = new Uint8Array(byteBuffer); // or UInt16Array
const typedArray = new Float32Array(quantized.length); // or Int32Array
for (let i = 0; i < a.length; i++) {
  typedArray[i] = quantized[i] * scale + min;
}
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/965#-:-LAt71ua1LQJEQbCPdph:bg85ia3)*

**Comment by dsmilkov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/weights_loader.ts, line 178 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/965#-LAt5ZOk3dhg_Yn5HzLj:-LAt7OBCD0ZCpl-pYHDl:b-1a9n26) ([raw file](https://github.com/tensorflow/tfjs-core/blob/37a204a847865de96ac91ef08356d8fac8fb132c/src/weights_loader.ts#L178)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

no need to have this intermediate Float32Array. Just allocate the final `typedArray `depending on the logical dtype (Int32Array or Float32Array). JS will give you all zeros if you use the c-tor with the size passed in.

Then iterate directly over the UIn8Array or UInt16Array (depending on the quantized dtype), and do the math directly there.

```ts
const quantized = new Uint8Array(byteBuffer); // or UInt16Array
const typedArray = new Float32Array(quantized.length); // or Int32Array
for (let i = 0; i < a.length; i++) {
  typedArray[i] = quantized[i] * scale + min;
}
```
</blockquote></details>

Forgot to say , if it's int32, round before you assign to typedArray[i]

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/965)*

**Comment by adarob** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/weights_loader.ts, line 128 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/965#-LAPRCzO66-puBZduxqv:-LAtkeTV9N1Ugq7FxvVb:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/ec2a93ade53cd60eb207a293d0fcf9ee2d8036d4/src/weights_loader.ts#L128)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

this should not be removed
</blockquote></details>

Done.

---

*[src/weights_loader.ts, line 178 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/965#-LAt5ZOk3dhg_Yn5HzLj:-LAu-K3hCoraTqpQjF_Y:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/37a204a847865de96ac91ef08356d8fac8fb132c/src/weights_loader.ts#L178)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Forgot to say , if it's int32, round before you assign to typedArray[i]
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/965)*

**Comment by adarob** [comment]
Done.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/965#-:-LAu1SGFDctWZS2Zyxke:b-896fix)*

**Comment by pyu10055** [comment]
Reviewed 1 of 2 files at r4.
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[src/weights_loader.ts, line 187 at r4](https://reviewable.io/reviews/tensorflow/tfjs-core/965#-LAv34I93rQXPMRX9WHM:-LAv34I93rQXPMRX9WHN:b-23ynju) ([raw file](https://github.com/tensorflow/tfjs-core/blob/648e8630b91c223a04a60f8a0d90964de5b3c2ef/src/weights_loader.ts#L187)):*
> ```XML
>         if (dtype === 'float32') {
>           dequantize = v => v * quantization.scale + quantization.min;
>           typedArray = new Float32Array(quantizedArray.length);
> ```

use typeArray = Float32Array.from(quantizedArray, v => v * quantization.scale + quantization.min), same for int32 case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/965)*

**Comment by pyu10055** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/965#-:-LAv3OZq2gbiXmQ9aO-k:b-jbsf8z)*

**Comment by pyu10055** [comment]
Reviewed 1 of 2 files at r4.
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/965)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Nice work Adam. I think the only outstanding comment is Ping's about using Float32Array.from(). After that I'll merge this in.

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[src/weights_loader.ts, line 187 at r4](https://reviewable.io/reviews/tensorflow/tfjs-core/965#-LAv34I93rQXPMRX9WHM:-LAx-Od81Muon9xkrLgB:b-cttm4c) ([raw file](https://github.com/tensorflow/tfjs-core/blob/648e8630b91c223a04a60f8a0d90964de5b3c2ef/src/weights_loader.ts#L187)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

use typeArray = Float32Array.from(quantizedArray, v => v * quantization.scale + quantization.min), same for int32 case.
</blockquote></details>

+1. This will create one less intermediate array

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/965#-:-LAx-TQT1eo__b4UhyEH:b-k3097d)*

**Comment by adarob** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[src/weights_loader.ts, line 187 at r4](https://reviewable.io/reviews/tensorflow/tfjs-core/965#-LAv34I93rQXPMRX9WHM:-LAxWyYs1iL1k3zul27i:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/648e8630b91c223a04a60f8a0d90964de5b3c2ef/src/weights_loader.ts#L187)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

+1. This will create one less intermediate array
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/965)*

**Pull request merged**
