### PR TITLE
Fix a firefox download issue 

### PR DESCRIPTION
**Pull request by rthadur**
#### Description

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1444)

### CODE REVIEW

**Comment by rthadur** [comment]
Sure , will create a helper method.

**Comment by rthadur** [comment]
Thanks @nsthorat ,will take a look at it

**Comment by nsthorat** [comment]
@rthadur was this ready for review? Sorry I missed this. Would you still want to land this if you rebase?

**Comment by rthadur** [comment]
@nsthorat i think this is fixed here #1613 ,will close this , thank you

**Pull request closed without merging**
