### PR TITLE
Allow squeeze to use negative index

### PR DESCRIPTION
**Pull request by VisibleMarkov**
Issue in focus: tensorflow/tfjs#940

#### Description

`squeeze()` didn't support the use of negative index which is supported in tensorflow for Python. Added tests for the same in `util_test` and `tensor_test`.
The previous implementation didn't allow for random arrangement of values of axis. For example if axes is set to `[2, 3]`, it would remove them both but if you pass it as `[3, 2]` it would only remove 3 and ignore 2 entirely. I tried the same with tensorflow for python in this [Google Colab Notebook](https://colab.research.google.com/drive/1jzyuRFXfIVrK50jI7vDrVuW5dYpiYw0V) and this too was inconsistent with tfjs as tensorflow python allows for removal of axis irrespective of order of input if it's allowed. This inconsistency was removed when adding the support for negative index ( it was totally unintentional but resulted from my implementation to allow negative index ).

Clarification required for following topics:
* I am not sure whether the test messages are satisfactory for the new tests added - Please let me know if this can be improved and I'll implement the same as soon as possible.
* The random input order support was a result of my judgement where i thought `[-1, -2]` was intuitively much better for a programmer but if we just replaced it with the positive index of same, it would have been `[5, 4]` which due to it's lack of ascending order would have ignored 4 completely. If this needs to changed, please let me know and I'll come up with another implementation to change this behavior.

Tests Ran:
* [x] yarn test
* [x] yarn lint

BUG

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: BUG

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1430)

### CODE REVIEW

**Comment by VisibleMarkov** [comment]
I signed it!

**Comment by VisibleMarkov** [comment]
* Added an exception case in case the given value of axis doesn't lie in `[ -shape.length, shape.length)` which further makes it consistent with tensorflow for python.
The behavior of Python in the case can be found in this [Google Colab Notebook](https://colab.research.google.com/drive/1jzyuRFXfIVrK50jI7vDrVuW5dYpiYw0V)

Seeking Clarification on following issue:
* The error message was more than 80 characters long and I suppressed TSist using `disable-line`. Please let me know if this can be replaced with a shorted message, or another approach altogether

Tests Ran:
* [x] yarn test
* [x] yarn lint

**Comment by VisibleMarkov** [comment]
@caisq Addressed the changes requested in 02d2344
If anything needs to be changed, please let me know and I'll implement it as soon as I can (^_^)

**Comment by VisibleMarkov** [comment]
Thanks for the green flag (^_^)
Just curious: Should I wait for another review by someone else?

**Comment by caisq** [comment]
@VisibleMarkov PR is merged. Thank you for your contribution!

**Pull request merged**
