### PR TITLE
remove old demos, move benchmarks to integration_tests

### PR DESCRIPTION
**Pull request by tafsiri**
Deletes the old demos. We are keeping benchmarks around but need to do some work to port them to our new tooling.

Added a README to this effect.

Closes tensorflow/tfjs#176 tensorflow/tfjs#62

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/943)

### CODE REVIEW

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: 0 of 83 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/943#-:-L9q7zkb4bbjwis0BY23:b-jbsf8z)*

**Comment by tafsiri** [comment]
@dsmilkov @nsthorat is there anyone we should @ mention in here to grab demos that they want to host/maintain elsewhere?

**Comment by dsmilkov** [comment]
Adding a few folks to start the conversation for transferring the code and hosting to the authors. Just want to point out that we are still hosting these models on deeplearnjs.org, but we won't be updating that website.

@cghawthorne for Performance RNN
@reiinakano for fast style transfer
@jameswex Teachable gaming
@shancarter for latent space explorer

**Comment by tafsiri** [comment]
I'm going to leave a link here for a useful tag for people who are looking to get the code for old demos https://github.com/tensorflow/tfjs-core/tree/v0.5.1

**Comment by cghawthorne** [comment]
The Performance RNN code is now available here: https://goo.gl/magenta/performancernn-demo-code
And the demo is hosted here: https://goo.gl/magenta/performancernn-demo

**Comment by dsmilkov** [comment]
Thanks @cghawthorne !

**Pull request merged**
