### PR TITLE
Add tensor6d()

### PR DESCRIPTION
**Pull request by jgartman**
#### Description

As described in the comments on this issue https://github.com/tensorflow/tfjs/issues/161 I think having a 6D sampler and  6D GPU `transpose` will be the best way to fully support the `batchToSpaceND` op.  This PR adds a 6D tensor type, GPU support for 6D tensors, GPU support for 6D `transpose` and tests for a few various ops.  Let me know if there should be more tests and I'll go ahead and add them.

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1084)

### CODE REVIEW

**Comment by dsmilkov** [comment]
:lgtm_strong: Really nice work Josh! Left couple tiny comments (one is my failed attempt to merge the conflict via github :)) Thank you!

---

Reviewed 5 of 12 files at r1, 7 of 7 files at r2.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/kernels/webgl/shader_compiler.ts, line 1048 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/1084#-LEzKEfT1EUpZh_Zu1PT:-LEzKEfT1EUpZh_Zu1PU:btbwih2) ([raw file](https://github.com/tensorflow/tfjs-core/blob/69680125f8f34cb65d43e797e3293127727833e3/src/kernels/webgl/shader_compiler.ts#L1048)):*
> ```XML
>   `;
> }=======
> 1063
> ```

hey sorry, I tried to merge the conflicts for you via GitHub, but apparently failed. Can you remove these 3 lines when you get a chance? Thanks!

---

*[src/ops/unary_ops_test.ts, line 726 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/1084#-LEzKsMz8XI9-IeRtdwi:-LEzKpY7EVtKRj5C07RK:b-k8jgm4) ([raw file](https://github.com/tensorflow/tfjs-core/blob/69680125f8f34cb65d43e797e3293127727833e3/src/ops/unary_ops_test.ts#L726)):*
> ```XML
>           1, 2, Math.sqrt(2),
>           Math.sqrt(
>               3,
> ```

I think this trailing comma after `3` confused clang-format

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1084#-:-LEzL2AF0leWxfmf9blX:b-1t1htl)*

**Comment by dsmilkov** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/kernels/webgl/shader_compiler.ts, line 1048 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/1084#-LEzKEfT1EUpZh_Zu1PT:-LEzLr685cJMwP-UVEkb:bakn61a) ([raw file](https://github.com/tensorflow/tfjs-core/blob/69680125f8f34cb65d43e797e3293127727833e3/src/kernels/webgl/shader_compiler.ts#L1048)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

hey sorry, I tried to merge the conflicts for you via GitHub, but apparently failed. Can you remove these 3 lines when you get a chance? Thanks!
</blockquote></details>

Nevermind. Nikhil merged another PR and gave me another chance to merge again :)

---

*[src/ops/unary_ops_test.ts, line 726 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/1084#-LEzKsMz8XI9-IeRtdwi:-LEzLySC8MIf9-5849m_:bulawv3) ([raw file](https://github.com/tensorflow/tfjs-core/blob/69680125f8f34cb65d43e797e3293127727833e3/src/ops/unary_ops_test.ts#L726)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

I think this trailing comma after `3` confused clang-format
</blockquote></details>

Nvm on this one. one can fix this in another PR if you feel like it!

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1084)*

**Comment by dsmilkov** [comment]
Hey Josh, I just synced to master and 40ish tests fail on Travis. In between when you started your PR, we added some optimization for uniforms in https://reviewable.io/reviews/tensorflow/tfjs-core/1087 See the changes to getSampler5D - you will have to incorporate those to your 6D samplers as well. Or just copy-paste the getSampler5D code from scratch and change it to 6D. Sorry for this. Thank you!

**Comment by jgartman** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/ops/unary_ops_test.ts, line 726 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/1084#-LEzKsMz8XI9-IeRtdwi:-LF5FVW539_HluLUkDY2:buyydde) ([raw file](https://github.com/tensorflow/tfjs-core/blob/69680125f8f34cb65d43e797e3293127727833e3/src/ops/unary_ops_test.ts#L726)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Nvm on this one. one can fix this in another PR if you feel like it!
</blockquote></details>

Fixed it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1084)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 2 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1084#-:-LFNISWw-CwtwhPq8ga-:b-jbsf8z)*

**Comment by nsthorat** [comment]
Thanks Josh!

**Pull request merged**
