### PR TITLE
Add implementation for resizeBilinear gradient.

### PR DESCRIPTION
**Pull request by tafsiri**
Also fixes a bug in resizeBilinear.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/996)

### CODE REVIEW

**Comment by tafsiri** [comment]
This now also has a GPU implementation!

**Comment by dsmilkov** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/kernels/backend_cpu.ts, line 1499 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaWDgl-6IMKeNTxXNr:-LBaWDgl-6IMKeNTxXNs:blkshn1) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/kernels/backend_cpu.ts#L1499)):*
> ```XML
>     for (let b = 0; b < batch; b++) {
>       for (let r = 0; r < yHeight; r++) {
>         const inY = r * heightScale;
> ```

keep row column notation. Since y and x are reserved for input tensor and output tensor.

---

*[src/kernels/backend_cpu.ts, line 1514 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaWauG22Wrdh77VPnU:-LBaWauG22Wrdh77VPnV:b1uld86) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/kernels/backend_cpu.ts#L1514)):*
> ```XML
>           for (let d = 0; d < depth; d++) {
>             let topLeft = output.get(b, topYIndex, leftXIndex, d);
>             topLeft += dy.get(b, r, c, d) * inverseYLerp * inverseXLerp;
> ```

Try to use direct flat indexing into the values (avoid calling .get) to speed it up. See https://reviewable.io/reviews/tensorflow/tfjs-core/995 for how conv2d got 100x faster.

---

*[src/kernels/webgl/resize_bilinear_backprop_gpu.ts, line 78 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaY5LG3YbOO2Tsnpd3:-LBaY5LG3YbOO2Tsnpd4:bypl5ah) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/kernels/webgl/resize_bilinear_backprop_gpu.ts#L78)):*
> ```XML
> 
>         // Loop over dy
>         for (int dry = 0; dry < int(${winHeight}); dry++) {
> ```

extract in a variable `int(${winHeight}` so you don't cast every tick of the for loop. Here and the for loop below.

---

*[src/kernels/webgl/resize_bilinear_backprop_gpu.ts, line 79 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaXthr4KzQwRcKaUz5:-LBaXthr4KzQwRcKaUz6:b-yhhvwv) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/kernels/webgl/resize_bilinear_backprop_gpu.ts#L79)):*
> ```XML
>         // Loop over dy
>         for (int dry = 0; dry < int(${winHeight}); dry++) {
>           int ry = dry + startRY;
> ```

in conv2d gpu we do dyR/dyC and row and column in dy.

---

*[src/ops/image_ops.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaZukA66so9yaFS17m:-LBaZukA66so9yaFS17n:b-gfpzq1) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/ops/image_ops.ts#L61)):*
> ```XML
> 
>     const [newHeight, newWidth] = size;
>     const forward: ForwardFunc<Tensor4D> = (backend, save) => save(
> ```

Don't save the result. Use shape from dy

---

*[src/ops/image_ops.ts, line 67 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaZPQq02lLmYrtxQLC:-LBaZPQq02lLmYrtxQLD:b-y3kypx) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/ops/image_ops.ts#L67)):*
> ```XML
>       const y = saved[0] as Tensor4D;
> 
>       const result = ENV.engine.runKernel(
> ```

make result a function that gets called by someone else. That is `const result = () => ENV.engine.runKernel(...`

---

*[src/ops/image_ops.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBa_8Vi07KoPCfvSaoI:-LBa_8Vi07KoPCfvSaoJ:bf2u7uh) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/ops/image_ops.ts#L69)):*
> ```XML
>       const result = ENV.engine.runKernel(
>           backend =>
>               backend.resizeBilinearGrad(dy, batchImages, y, alignCorners),
> ```

no need to pass y, which means no need you have `y = saved[0]`

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/996)*

**Comment by dsmilkov** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/ops/resize_bilinear_test.ts, line 179 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaajThDN6pS0iLJ_72:-LBaajThDN6pS0iLJ_73:b-kyezj8) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/ops/resize_bilinear_test.ts#L179)):*
> ```XML
>       [[9.0], [10.0], [11.0], [12.0]], [[13.0], [14.0], [15.0], [16.0]]
>     ]);
>     const g = tf.grad(resize.bind(null, [4, 4], false));
> ```

```ts
const size = [4, 4];
const alignCorners = false;
const g = tf.grad(image => tf.image.resizeBilinear(image, size, alignCorners));
g(image, dy);
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/996)*

**Comment by tafsiri** [comment]
Ready for re-review

---

Review status: 1 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/kernels/backend_cpu.ts, line 1499 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaWDgl-6IMKeNTxXNr:-LBagtTL3tf06053NMEl:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/kernels/backend_cpu.ts#L1499)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

keep row column notation. Since y and x are reserved for input tensor and output tensor.
</blockquote></details>

Done.

---

*[src/kernels/backend_cpu.ts, line 1514 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaWauG22Wrdh77VPnU:-LBbIT8TE1H_pq6aDEcF:b64kpyl) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/kernels/backend_cpu.ts#L1514)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Try to use direct flat indexing into the values (avoid calling .get) to speed it up. See https://reviewable.io/reviews/tensorflow/tfjs-core/995 for how conv2d got 100x faster.
</blockquote></details>

Not yet done. If this PR looks good i'd like to try do that in a separate PR (just so that this one doesn't delay in the mean time). 

---

*[src/kernels/webgl/resize_bilinear_backprop_gpu.ts, line 78 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaY5LG3YbOO2Tsnpd3:-LBahmHmBAYuY4aYAIB3:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/kernels/webgl/resize_bilinear_backprop_gpu.ts#L78)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

extract in a variable `int(${winHeight}` so you don't cast every tick of the for loop. Here and the for loop below.
</blockquote></details>

Done.

---

*[src/kernels/webgl/resize_bilinear_backprop_gpu.ts, line 79 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaXthr4KzQwRcKaUz5:-LBanLng8JKPsG7Tt5p6:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/kernels/webgl/resize_bilinear_backprop_gpu.ts#L79)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

in conv2d gpu we do dyR/dyC and row and column in dy.
</blockquote></details>

Done.

---

*[src/ops/image_ops.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaZukA66so9yaFS17m:-LBaeK2XDWkV4BnJKZ9p:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/ops/image_ops.ts#L61)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Don't save the result. Use shape from dy
</blockquote></details>

Done.

---

*[src/ops/image_ops.ts, line 67 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaZPQq02lLmYrtxQLC:-LBaeQcP6gdMaP8_6-8F:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/ops/image_ops.ts#L67)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

make result a function that gets called by someone else. That is `const result = () => ENV.engine.runKernel(...`
</blockquote></details>

Done.

---

*[src/ops/image_ops.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBa_8Vi07KoPCfvSaoI:-LBaecOF5ANZB9SPIstK:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/ops/image_ops.ts#L69)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

no need to pass y, which means no need you have `y = saved[0]`
</blockquote></details>

Done.

---

*[src/ops/resize_bilinear_test.ts, line 179 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-LBaajThDN6pS0iLJ_72:-LBbIkTT8w9YWRra-kKx:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/1468028867f8746c3b290f0750b80cf924e48268/src/ops/resize_bilinear_test.ts#L179)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

```ts
const size = [4, 4];
const alignCorners = false;
const g = tf.grad(image => tf.image.resizeBilinear(image, size, alignCorners));
g(image, dy);
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/996#-:-LBbIoWcEestRggQJToO:b-6drotj)*

**Pull request merged**
