### PR TITLE
Xor Eager: Adds Xor eager mode demo

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR adds Learning Xor eager mode demo.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/804)

### CODE REVIEW

**Comment by nsthorat** [comment]
Hi Manraj,

Can you hold onto this change for a little bit? We'll have a better place for these demos in the next 3 weeks.

**Comment by ManrajGrover** [comment]
Hi Nikhil,

Yeah sure! I'll wait for an update.

**Comment by hpssjellis** [comment]
@ManrajGrover 

I think  `cost.getValues()` will be deprecated with version 0.60. probably should use `cost.dataSync()`

used at line 80 

> console.log(`loss[${i}]: ${cost.getValues()}`);

The Github location is 
https://github.com/ManrajGrover/deeplearnjs/blob/xor-eager/demos/xor-eager/learn-xor.ts#L80

**Comment by dsmilkov** [comment]
Hi,

The team had some discussion and we decided to keep the number of [examples](https://github.com/tensorflow/tfjs-examples) small, so that it is easier to maintain. We would love to see this in an [Observable notebook](https://beta.observablehq.com/) and happy to provide guidance while moving the code there.

**Pull request closed without merging**
