### PR TITLE
Add tf.spaceToBatchND

### PR DESCRIPTION
**Pull request by dikatok**
#### Description
Adds batchToSpaceND to the API [tensorflow/tfjs#161](tensorflow/tfjs#161).

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1176)

### CODE REVIEW

**Comment by dikatok** [comment]
@rodrigob the only interaction I can think of is using them to implement atrous convolution, or do you have any suggestions?

**Comment by rodrigob** [comment]
@dikatok I have not studied the operations definition in detail, but is there not an expected symmetry ?

Something like 
assert A == spaceToBatchND( batchToSpaceND( A ) ) ?

**Comment by dikatok** [comment]
@rodrigob hmmm ok I will add some symmetry tests

**Comment by dsmilkov** [comment]
@rodrigob That's a great suggestion

**Comment by dikatok** [comment]
whoops, forgot to ping you @dsmilkov

**Pull request merged**
