### PR TITLE
Reduction Ops: Adds tf.all to the API

### PR DESCRIPTION
**Pull request by ManrajGrover**
#### Description
This PR adds `tf.all` to the API. This partially fixes https://github.com/tensorflow/tfjs/issues/430.

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1104)

### CODE REVIEW

**Comment by bileschi** [comment]
Thanks @ManrajGrover !   It appears that some of the test you wrote failed in some environments.  Can you take a look?  Thanks.

https://travis-ci.org/tensorflow/tfjs-core/jobs/392629562

**Comment by ManrajGrover** [comment]
@bileschi It seems like the error is related to precision and is specific to `Mobile Safari 11.0.0 (iOS 11.0.1)`. It looks like precision is set to `highp` for `float` yet the shader fails in compilation. I would need some inputs from @nsthorat on this.

**Comment by nsthorat** [comment]
I don't know exactly *why* the error is happening, but I checked out your branch and fixed it by not using bools in the updateSnippet.

```
      updateSnippet = \`
        float reducedAllValue = dot(vec4(1.0), values);
        allValue = float(
          allValue >= 1.0 && float(reducedAllValue) >= numValues);
      \`;
```

"numValues" should be 4 when using full vec4, 3 when using vec3, etc.

```
        vec4 minMaxValue = vec4(${initializationValue});
        float sumValue = 0.0;
        float allValue = 1.0;
        // Add this line
        float numValues = 4.0;
```

and then before each updateSnippet call, change "numValues", e.g.:

```
} else if (${windowSizeVec4Remainder === 3}) {
          ${vecType} values = ${vecType}(
            getValue(batch, inIdx),
            getValue(batch, inIdx + 1),
            getValue(batch, inIdx + 2),
            initializationValue
          );

          numValues = 3.0;
          ${updateSnippet}
        }
```

But of course in all the places.

Try this and your unit tests should pass!

**Comment by ManrajGrover** [comment]
@nsthorat Thanks for looking into it. I was thinking of debugging it a little. If the current approach doesn't work, I'll make changes as per your approach. :)

**Comment by ManrajGrover** [comment]
@nsthorat It seems to be fixed. This must be because of implicit typecasting of `reducedAllValue` from `boolean` to `float` on line:

```cpp
allValue = float(allValue >= 1.0 && float(reducedAllValue) >= numValues);
```

Making it explicit fixes the precision issue:

```cpp
float floatedReducedAllValue = float(reducedAllValue);
allValue = float(allValue >= 1.0 && floatedReducedAllValue >= 1.0);
```

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1104#-:-LFNNSjR7d41lk411VYS:b-jbsf8z)*

**Pull request merged**
