### PR TITLE
fixed shader_compile shader's syntax error in glsl 4.1

### PR DESCRIPTION
**Pull request by adarabi**
sample and texture are reserved keywords in glsl 4.1: 
https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.10.pdf

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/921)

### CODE REVIEW

**Comment by adarabi** [comment]
I signed it!

**Comment by nsthorat** [comment]
Just curious - are you seeing a compile error? We've never seen an error with this before.

**Comment by nsthorat** [comment]
Cool, thanks for the explanation. Could you respond with "I signed it!" from github, I think the CLA doesn't like the email response.

**Comment by adarabi** [comment]
I signed it!

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/921#-:-L9LwbxcBTnMy0e3WTFP:b-jbsf8z)*

**Comment by nsthorat** [comment]
Thanks for the fix!

**Comment by adarabi** [comment]
@nsthorat is it possible you release a new version with this fix so we can migrate to tf-js from deeplearn?
thank you

**Pull request merged**
