### PR TITLE
fix: update tsconfig.json

### PR DESCRIPTION
**Pull request by HRK44**
Add 'dist' directory to remove some TS compilation error.
See https://github.com/Microsoft/TypeScript/issues/17155 for more info

#### Description

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1102)

### CODE REVIEW

**Comment by HRK44** [comment]
I signed it!

**Comment by HRK44** [comment]
When you open the ``tsconfig.json`` file from ``node_modules/@tensorflow/tfjs-core`` on VSCode, it underlines the whole file in red with this error : 

``No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["src/"]' and 'exclude' paths were '[""]'.``

There is no ``src`` folder in the bundled version, I think that's why.

screenshot from 2018-06-18 09-46-53

**Comment by HRK44** [comment]
Also the tsconfig-es5.json?

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1102#-:-LFIKJ8h5Q_wn_VboXb7:b-jbsf8z)*

**Comment by HRK44** [comment]
Ok so I reverted the change in the tsconfig.json and added it to .npmignore

**Comment by nsthorat** [comment]
Thank you @HRK44 !

**Pull request merged**
