### PR TITLE
Add batchToSpaceND op

### PR DESCRIPTION
**Pull request by jgartman**
#### Description

Adds `batchToSpaceND` to the API https://github.com/tensorflow/tfjs/issues/161.  

Just wanted to make sure the approach I used here is acceptable.  The op is composed out of existing ops but is implemented in `backend_webgl` and `backend_cpu`.  This was done so that the node.js bindings can use the op but it seems a bit unusual since other ops in the library that are composed from existing ops don't typically call into the backend directly.  Let me know and I can rework as needed.

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1121)

### CODE REVIEW

**Comment by rodrigob** [comment]
@pyu10055 opinions on this PR ?

**Comment by rodrigob** [comment]
@jgartman  src/ops/array_ops_uitl.ts  should be renamed to array_ops_util.ts

**Comment by pyu10055** [comment]
Thanks!

---

Reviewed 8 of 8 files at r1.
Review status: 0 of 1 LGTMs obtained

---

*[src/ops/array_ops_uitl.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1121#-LFwvNTb7yTJVDjzVqXu:-LFwvNTb7yTJVDjzVqXv:bw9dvku) ([raw file](https://github.com/tensorflow/tfjs-core/blob/35cbe83050b425c7be0a96e70b00f78c18fbac19/src/ops/array_ops_uitl.ts#L18)):*
> ```
> getReshapedBatchDim
> ```
please add comments to the helper functions defined here.

---

*[src/ops/array_ops_uitl.ts, line 27 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1121#-LFwvaVa7jZmnzrmK4_i:-LFwvaVa7jZmnzrmK4_j:b-l26upb) ([raw file](https://github.com/tensorflow/tfjs-core/blob/35cbe83050b425c7be0a96e70b00f78c18fbac19/src/ops/array_ops_uitl.ts#L27)):*
> ```XML
> 
> export function getInputAndBlockPermutation(
>     reshaped: number[], blockShapeRank: number): number[] {
> ```

since this method does not use values of reshaped, just passing the length of reshaped.

---

*[src/ops/array_ops_uitl.ts, line 60 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1121#-LFx35JO-8HHhRfnMwX3:-LFx35JO-8HHhRfnMwX4:b24xciw) ([raw file](https://github.com/tensorflow/tfjs-core/blob/35cbe83050b425c7be0a96e70b00f78c18fbac19/src/ops/array_ops_uitl.ts#L60)):*
> ```XML
>   }
> 
>   for (let i = blockShape; uncroppedRank - 2 > i; ++i) {
> ```

why uncroppedRank -2, not including the last dimension?

---

*[src/ops/array_ops_uitl.ts, line 70 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1121#-LFx3Deq5UGrfTh7QW9q:-LFx3Der1V7xwYe8WKOU:b-7um49n) ([raw file](https://github.com/tensorflow/tfjs-core/blob/35cbe83050b425c7be0a96e70b00f78c18fbac19/src/ops/array_ops_uitl.ts#L70)):*
> ```XML
>   const resultShape = uncroppedShape.slice(0, 1);
>   for (let i = 0; i < blockShape; ++i) {
>     resultShape.push(uncroppedShape[i + 1] - crops[i][0] - crops[i][1]);
> ```

should it also include the size as -1 for the rest of the dimensions blockShape +1 : uncroppedShape.length -1 ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1121#-:-LFx3XQf4nD1zV3siTrv:b-ucfknh)*

**Comment by jgartman** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[src/ops/array_ops_uitl.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1121#-LFwvNTb7yTJVDjzVqXu:-LG8FyTK5UHQDzMGU4Ou:b-jd9gd2) ([raw file](https://github.com/tensorflow/tfjs-core/blob/35cbe83050b425c7be0a96e70b00f78c18fbac19/src/ops/array_ops_uitl.ts#L18)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> getReshapedBatchDim
> ```
please add comments to the helper functions defined here.
</blockquote></details>

Done, I also renamed the functions to match the names given in the steps in the documentation.  Hopefully its a bit clearer now.

---

*[src/ops/array_ops_uitl.ts, line 27 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1121#-LFwvaVa7jZmnzrmK4_i:-LG8GCsMCL-B5rQ74ZoH:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/35cbe83050b425c7be0a96e70b00f78c18fbac19/src/ops/array_ops_uitl.ts#L27)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

since this method does not use values of reshaped, just passing the length of reshaped.
</blockquote></details>

Done.

---

*[src/ops/array_ops_uitl.ts, line 60 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1121#-LFx35JO-8HHhRfnMwX3:-LG8GDXnBIEb0UlbH3Ic:bok4619) ([raw file](https://github.com/tensorflow/tfjs-core/blob/35cbe83050b425c7be0a96e70b00f78c18fbac19/src/ops/array_ops_uitl.ts#L60)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

why uncroppedRank -2, not including the last dimension?
</blockquote></details>

You're right about this, that loop was never being run.  Looking over the slice documentation it looks like if the rank of the `begin` argument is less than the rank of `x` it just assumes that rest of the axes start at 0.  Since this is what we want anyway I think it should be fine to get rid of this loop altogether.

---

*[src/ops/array_ops_uitl.ts, line 70 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1121#-LFx3Deq5UGrfTh7QW9q:-LG8HDufAYieTjrim41_:bo352nn) ([raw file](https://github.com/tensorflow/tfjs-core/blob/35cbe83050b425c7be0a96e70b00f78c18fbac19/src/ops/array_ops_uitl.ts#L70)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should it also include the size as -1 for the rest of the dimensions blockShape +1 : uncroppedShape.length -1 ?
</blockquote></details>

Similar to above, you're right but if the rank of the `size` argument is less than the rank of `x` the rest of the axes will have an implicit -1.  If you think -1 should be added explicitly for the remaining axes for clarity I can do that though.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1121)*

**Comment by rodrigob** [comment]
I have not inspected the code, what is the status of this PR ?

@pyu10055

**Comment by nsthorat** [comment]
Hey @jgartman, just following up with Daniel's comment about taking on SpaceToBatch, there's a super interesting application of TensorFlow.js that needs this op :)

**Comment by jgartman** [comment]
@nsthorat I would but reading over the issue tracker it looks like another contributor has been working on it and expects to be done soon.

**Pull request merged**
