### PR TITLE
CPU/GPU consistency for pow

### PR DESCRIPTION
**Pull request by jgartman**
#### Description

This PR makes the output of the pow function more consistent on WebGL vs. the CPU https://github.com/tensorflow/tfjs/issues/350.  This change will cause the function to output `nan` when a negative base is taken to a fractional exponent.

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1136)

### CODE REVIEW

**Comment by nsthorat** [comment]
Thanks for the PR! Just curious, do you know if this is how TensorFlow python behaves?

---

Review status: 0 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1136#-:-LGRgTFq8cOm34zxona5:b-m58sab)*

**Comment by jgartman** [comment]
TensorFlow python does return `nan` for a negative base taken to a fractional exponent however there are still some other differences with the tfjs implementation.  TF is stricter about both the arguments having the same type but based on this discussion https://github.com/tensorflow/tfjs-core/pull/1129  it doesn't seem like  that's a concern.  TF will also throw an error when an int32 base and exponent are used and the exponent is negative but again I thought that was stricter than necessary here.  Just to give a little background, the primary motivation for this PR was this discussion https://github.com/tensorflow/tfjs/issues/346 about how to fix the gradient for pow.

Note that the testing I did with TF python was CPU only.

---

Review status: 0 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1136#-:-LGSkXNxDmUm3uzsh_Qv:b-rnbyug)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1136#-:-LGVVT5f-7frXWa7b3n9:b-jbsf8z)*

**Comment by nsthorat** [comment]
Thanks @jgartman!! P.S. you should still shoot me an email, I can't find your email anywhere :)

**Comment by jgartman** [comment]
Will do @nsthorat and if you ever need my email its my firstname.lastname at gmail.

**Pull request merged**
