### PR TITLE
Adds tf.atan2

### PR DESCRIPTION
**Pull request by jgartman**
Adds `tf.atan2` to the API

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/913)

### CODE REVIEW

**Comment by nsthorat** [comment]
This is absolutely awesome. Thank you for paying attention to detail, writing high-coverage unit tests and writing the gradient.

I have a few minor minor comments and then I will merge this!

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---

*[src/ops/binary_ops.ts, line 466 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/913#-L8yG6m51QIuubC037mJ:-L8yG6m51QIuubC037mK:b-3n9dm8) ([raw file](https://github.com/tensorflow/tfjs-core/blob/2414777655ce63d36b501c9bfb2b3e788c5ee8a9/src/ops/binary_ops.ts#L466)):*
> ```XML
> 
>   /*
>    * Computes arctangent of 'Tensor's a / b element-wise: `atan2(a, b)`.
> ```

Can you use backticks for Tensor

---

*[src/ops/binary_ops.ts, line 473 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/913#-L8yGJK-Bc52OGqOlx7q:-L8yGJK-Bc52OGqOlx7r:buhjcbw) ([raw file](https://github.com/tensorflow/tfjs-core/blob/2414777655ce63d36b501c9bfb2b3e788c5ee8a9/src/ops/binary_ops.ts#L473)):*
> ```XML
>    * const b = tf.tensor1d([2.0, 13.0, 3.5, .21]);
>    *
>    * tf.atan2(x, y)
> ```

tf.atan2(x, y).print();

---

*[src/ops/binary_ops.ts, line 474 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/913#-L8yGM66DkCnID0NtXi0:-L8yGM66DkCnID0NtXi1:b-foh3zi) ([raw file](https://github.com/tensorflow/tfjs-core/blob/2414777655ce63d36b501c9bfb2b3e788c5ee8a9/src/ops/binary_ops.ts#L474)):*
> ```XML
>    *
>    * tf.atan2(x, y)
>    *
> ```

Missing 3 backticks to end the js block

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/913#-:-L8yHaZ69qMJV3oczLFh:b-iwx0i2)*

**Comment by jgartman** [comment]
Thanks @nsthorat, I updated the PR to address your comments.

**Comment by nsthorat** [comment]
Thanks! Almost there the three ticks are in wrong place :)

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/ops/binary_ops.ts, line 473 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/913#-L8yGJK-Bc52OGqOlx7q:-L8ygEM5DSNgadMqd-in:b-ajnb4w) ([raw file](https://github.com/tensorflow/tfjs-core/blob/2414777655ce63d36b501c9bfb2b3e788c5ee8a9/src/ops/binary_ops.ts#L473)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

tf.atan2(x, y).print();
</blockquote></details>

Add a semicolon here (we have a tool that will automatically run these and lint them which will fail in the future)

---

*[src/ops/binary_ops.ts, line 474 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/913#-L8yGM66DkCnID0NtXi0:-L8ygBbEEoiZZU5H891Y:bbhwoyr) ([raw file](https://github.com/tensorflow/tfjs-core/blob/2414777655ce63d36b501c9bfb2b3e788c5ee8a9/src/ops/binary_ops.ts#L474)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Missing 3 backticks to end the js block
</blockquote></details>

Oops, I think this is in the wrong place :)

You should add the 3 backticks after the print() line (not after these params)

The JS block above will be rendered as a code snippet in our docs page: https://js.tensorflow.org/api/0.6.1/

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/913#-:-L8ygSbcDgNRkNH8RY-b:bst5lny)*

**Comment by jgartman** [comment]
Oops, sorry @nsthorat, added another commit, hopefully I'll get this right eventually.

**Comment by nsthorat** [comment]
Looks good, merged! Thank you for the awesome PR!

**Pull request merged**
