### PR TITLE
Add tf.util.range()

### PR DESCRIPTION
**Pull request by caisq**
Compatible with `np.arange()`.

Fixes https://github.com/tensorflow/tfjs/issues/1049

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1468)

### CODE REVIEW

**Comment by caisq** [comment]
@nsthorat Yes. As I commented in the issue https://github.com/tensorflow/tfjs/issues/1049, I think a method like this will still be useful, because `tf.range()` returns a tensor, not an array of numbers. It's cumbersome to get an uniformly spaced array of numbers by using a tensor method, because the it'd be necessary to call data() or dataSync() and do memory management.

**Comment by DirkToewe** [comment]
Maybe a Generator instead of an Array output might be worth considering:
```js
function* range( start, end, step ) {
  // ...
  for( let i=0; i < end; i+=step )
    yield i
}
```
This way, less memory is used and it can still easily be converted into an Array using `[...tf.range(start,end,step) ]`.

**Comment by caisq** [comment]
@DirkToewe I like that idea. I think we should support both an array return type and a generator return type The former is easier to use and just works for smallish problems. The latter scales up well. How about I make the signature of the function like  `function range(start, end, step, isGenerator = false)`?

**Comment by nsthorat** [comment]
To be honest I wouldn't worry about memory consumption too much on the CPU. Let's cross that bridge if we find this to be a problem in practice. At the end of the day you're likely to store that as a TypedArray anyways.

Also, one more question, what are you going to use this for? Maybe return a TypedArray so that this is much faster?

**Comment by DirkToewe** [comment]
Not sure if the question is directed at me or @caisq. Personally,I'm probably not gonna use it since I would rather use either [itertools](https://www.npmjs.com/package/itertools) or something like `Float32Array.from({length: 1337}, (_,i) => 10*i)`. In Python, range is used as way more idiomatic replacement of the awful C-style `for(;;)` loop which is prone to terrible and sometimes hilarious mistakes.
```js
for( const i of tf.arange(100) )
for( const j of tf.arange(100) )
  // ...
```
Is way more idiomatic than:
```
for( let i=0; i < 100; i++ )
for( let j=0; j < 100; i++ )
  // ...
```

(I hid an bug in the `for(;;)` loop just to point out how problematic it is)

If that is what @caisq had in mind, using a generator would be preferrable (Python first introduced [xrange](https://www.geeksforgeeks.org/range-vs-xrange-python/) and then changed `range` to a generator in Python 3 because creating a `list`, everytime `range()` is called, turned out to be a memory and performance issue).

**Comment by nsthorat** [comment]
Gentle ping on this -- going through all the tfjs-core PRs.

**Comment by nsthorat** [comment]
Gentle ping, what's going on with this?

**Comment by caisq** [comment]
The use case isn't super clear. Closing this PR for now.

**Pull request closed without merging**
