### PR TITLE
add tf.diag

### PR DESCRIPTION
**Pull request by kedevked**
mimic python tf.diag

---
FEATURE https://github.com/tensorflow/tfjs/issues/639

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1256)

### CODE REVIEW

**Comment by kedevked** [comment]
I made the changes as suggested. But instead of returning a tensor2d the gpu backend is returning a tensor1d that is reshaped in `diag.ts`.
I have added more tests with tensor3d and tensor4d

**Comment by kedevked** [comment]
With output of 2D, we cannot compute the diagonal of tensor whose dimension is greater than 1. The issue that rises is the following: if the output is 2D, we only have to compare 2 coordinates, but when the tensor that is returned should be a 4D, 6D, 8D, ... we respectively have to compare 4, 6 and 8 coordinates. We cannot simply do it with getOutputCoords on a 2d output. That is why I wrote two helper functions `indextoCoords` and `coordstoIndex`.
`indextoCoords` will take the index of the 1D input and give his coordinates given the shape of the initial tensor and `coordstoIndex ` is useful to getX at a coordinate.

**Comment by kedevked** [comment]
Everything is fixed now, I think.

**Comment by dsmilkov** [comment]
CLA is ok because the other commits are from me (merging with master)

**Comment by kedevked** [comment]
Thanks  @dsmilkov for merging this code. There is also the related operator [tensorflow/tfjs#655](tensorflow/tfjs#655)

**Pull request merged**
