### PR TITLE
Initial coverage generation support (also: do not instrument normal tests)

### PR DESCRIPTION
**Pull request by ChALkeR**
This adds `npm run coverage` script, which produces coverage output in two formats: `text-summary` (to console) and `html` (detailed output written to `./coverage/` dir).

It does not introduce Travis + coveralls.io/codecov.io integration yet, this is just the first step aimed at getting coverage reports locally.

This also disables Istanbul instrumentation for all files during normal non-coverage tests, which were previously enabled for all tests.

To demonstrate the last clause:
  1. Check out `master`, run `npm it` (or `npm install && npm run test`), while the tests are running, open these two locations (adjust karma port if needed): http://localhost:9876/base/src/common.js and http://localhost:9876/base/src/common_test.js.
  Observe that the code is instrumented.
  Imo, that doesn't make much sense — coverage reporting seems to be disabled, coverage tests are also not used, and there seem to be performance warnings enabled.
  2. Check out this PR, run `npm t`, open those two urls again while the tests are running.
      Observe that the code of those two files is *not* instrumented.
  3. Check out this PR, run `npm run coverage`, open those two urls again while the tests are running.
      Observe that the code of `common.js` is instrumented while the code of `common_test.js` is not — instrumentation of test files was explicitly disabled.
  4. Observe the coverage summary and `./coverage` dir with HTML output being created at the previous step.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1132)

### CODE REVIEW

**Comment by ChALkeR** [comment]
Related: https://github.com/tensorflow/tfjs-layers/pull/254, https://github.com/tensorflow/tfjs-node/pull/110.

**Comment by dsmilkov** [comment]
:lgtm_strong: Thanks! This looks very helpful!

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1132#-:-LGAmVE52nmK7trdfF_U:b7p4ios)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 2 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1132#-:-LGAtGi549VOBlKY0N5U:b-jbsf8z)*

**Comment by nsthorat** [comment]
This is great, thank you very much. 93% line coverage, not bad :)

**Pull request merged**
