### PR TITLE
Ensure that tf.exp() uses non-int32 tensors.

### PR DESCRIPTION
**Pull request by nkreeger**
Fixes https://github.com/tensorflow/tfjs/issues/445#event-1687297929

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1129)

### CODE REVIEW

**Comment by nsthorat** [comment]
Can we actually solve this by relaxing the requirement in node by casting to a float32 if it's an integer?

**Comment by nkreeger** [comment]
We could - but then we differentiate from the TF api:
https://www.tensorflow.org/api_docs/python/tf/exp

**Comment by nsthorat** [comment]
Yep, I know, but it's a bit of a strange requirement to have tf.exp not allow integers.

**Comment by dsmilkov** [comment]
Based on a few reports on github and the mailing list, there is a need to relax tfjs API to allow mixing ints and floats (e.g. allowing `mul(int, float)`, `add(int, float)` etc). This makes the API different from TF, but not in a way that will hurt the user, yet improve usability of the library.

**Comment by nkreeger** [comment]
Closing and fixing in https://github.com/tensorflow/tfjs-node/pull/107

**Pull request closed without merging**
