### PR TITLE
Add fromPixels test

### PR DESCRIPTION
**Pull request by WenheLI**
This pr is related with https://github.com/tensorflow/tfjs/issues/1665 that adds tests for ``HTMLCanvasElement``, ``HTMLImageElement`` and ``HTMLVideoElemment``.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1794)

### CODE REVIEW

**Comment by nsthorat** [comment]
The two consecutive blank lines are making your presubmit fail (See "details" next to  Trigger: ed916b23-8e01-4fda-85af-b7c8627d15a1)

**Comment by WenheLI** [comment]
@nsthorat Thanks for pointing out that. And I am sorry for forgetting the lint check here.
In addition, since I do not have permission for checking the details about the unit test and the unit test passes under my local environment, could you help me check it out?

**Comment by nsthorat** [comment]
Just added some info here: https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md

You have to join one of the mailing lists to see the cloud builds!

**Comment by WenheLI** [comment]
@nsthorat Thanks! It turns out that the Safari do not accept empty img tag. I added a base64 img to make it safe.

**Pull request merged**
