### PR TITLE
adds pull request template

### PR DESCRIPTION
**Pull request by bileschi**
DEV adds default pull request template to help remind contributors to use PR commit message tags.

image

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1036)

### CODE REVIEW

**Comment by nsthorat** [comment]
Thanks for looking into this.

So the PR description isn't actually what matters, it's what we end up putting in the git commit message. Is there a way to set up the template for that instead?

**Comment by nsthorat** [comment]
And to be clear, the PR description doesn't automatically get added to the commit message.

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1036#-:-LCVSTK10xe5fA__S7WK:b-jbsf8z)*

**Comment by caisq** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1036#-:-LCVTtU_8_X1ggsMbMzf:b-jbsf8z)*

**Comment by dsmilkov** [comment]
We still need to manually copy the PR desc into the commit message when we squash and merge right? or does this template show up in the squash-and-merge message as well?

**Comment by bileschi** [comment]
@dsmilkov The user still needs to write their own squash & merge commit message.

Unfortunately there does not seem to be a good way to automatically populate the commit message.  It would require modifying the `.git/config` in a way that would not survive cloning the repo.  We could hack something up, perhaps a script, which modifies the user's config, but that sounds pretty risky & ugly.

**Comment by nsthorat** [comment]
We still have to copy paste it, but this will at least help us remember.

**Comment by ManrajGrover** [comment]
I feel we should move templates and contributing file to `.github` folder which seems to be a [general convention](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/).

**Comment by ManrajGrover** [comment]
I was thinking if we can automate adding PR title as commit title and PR description as commit description. Turns out there is already a Chrome extension that does it. Sharing it here: https://github.com/sindresorhus/refined-github

**Comment by dsmilkov** [comment]
I installed the extension and works great for me (copies the PR title and description into the commit)!

**Pull request merged**
