### PR TITLE
Refactor IO-related code to use the new LoadOptions interface

### PR DESCRIPTION
**Pull request by caisq**
- Refactor several IO-related functions to use the new `LoadOptions` interface.
- Move `monitorProgress` to the io-specific source directory.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1554)

### CODE REVIEW

**Comment by nsthorat** [comment]
Ideally we get this in this week before 1.0, is that right?

**Comment by nsthorat** [comment]
(let me know when to review)

**Comment by caisq** [comment]
@nsthorat There are a bunch of conflicts to resolve. I'll let you know when it's ready.

**Comment by caisq** [comment]
@nsthorat @dsmilkov @pyu10055 ready for review.

**Pull request merged**
