### PR TITLE
Inference model

### PR DESCRIPTION
**Pull request by pyu10055**
add input/output info to the inference model interface.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1089)

### CODE REVIEW

**Comment by caisq** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[src/types.ts, line 151 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1089#-LESAUxWAq8vfkSCqlm-:-LESAUxWAq8vfkSCqlm0:bxrilq3) ([raw file](https://github.com/tensorflow/tfjs-core/blob/996810db6c76bb26a6552fc0d99d29138359e135/src/types.ts#L151)):*
> ```
> // ten
> ```

Nit.  Capitalize first letter to be consistent with above. Same below.

---

*[src/types.ts, line 152 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1089#-LESAZr165BrZFXNsGkR:-LESAZr165BrZFXNsGkS:b-j1zitj) ([raw file](https://github.com/tensorflow/tfjs-core/blob/996810db6c76bb26a6552fc0d99d29138359e135/src/types.ts#L152)):*
> ```
> shape?:
> ```

Why is shape optional? Under what circumstance can shape be missing? Why is dtype not optional?

---

*[src/types.ts, line 153 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1089#-LESAhmHEf5xoOdroyeY:-LESAhmHEf5xoOdroyeZ:b-i8ld5r) ([raw file](https://github.com/tensorflow/tfjs-core/blob/996810db6c76bb26a6552fc0d99d29138359e135/src/types.ts#L153)):*
> ```
>  data type
> ```

Nit: end with a period.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1089)*

**Comment by pyu10055** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/types.ts, line 151 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1089#-LESAUxWAq8vfkSCqlm-:-LEau2xmDP8E3h6yzkQm:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/996810db6c76bb26a6552fc0d99d29138359e135/src/types.ts#L151)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> // ten
> ```

Nit.  Capitalize first letter to be consistent with above. Same below.
</blockquote></details>

Done.

---

*[src/types.ts, line 152 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1089#-LESAZr165BrZFXNsGkR:-LEau3T8D7ymdzRK6Gcu:b-i70d6q) ([raw file](https://github.com/tensorflow/tfjs-core/blob/996810db6c76bb26a6552fc0d99d29138359e135/src/types.ts#L152)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> shape?:
> ```

Why is shape optional? Under what circumstance can shape be missing? Why is dtype not optional?
</blockquote></details>

When the shape information is not set, it means it can take any shape of tensor. Take a look at https://www.tensorflow.org/api_docs/python/tf/placeholder

---

*[src/types.ts, line 153 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1089#-LESAhmHEf5xoOdroyeY:-LEauY6-Ab2tPl9meQSQ:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/996810db6c76bb26a6552fc0d99d29138359e135/src/types.ts#L153)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
>  data type
> ```

Nit: end with a period.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1089)*

**Comment by nsthorat** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/types.ts, line 167 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/1089#-LEf1rDh78_9Ra-wvAa8:-LEf1rDh78_9Ra-wvAa9:b-ooz1en) ([raw file](https://github.com/tensorflow/tfjs-core/blob/0ed85bb92b99eb299e34efcabfd33575de9d5879/src/types.ts#L167)):*
> ```XML
>    * Return the array of output tensor info.
>    */
>   getOuputs(): TensorInfo[];
> ```

getOutputs

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1089)*

**Comment by dsmilkov** [comment]
:lgtm_strong: (one typo to fix). Would be good for wait also for Shanqing's LGTM too since this intersects with Layers.

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/types.ts, line 167 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/1089#-LEf1rDh78_9Ra-wvAa8:-LEu6B7z03ovUyKH0Isc:b-jzntfl) ([raw file](https://github.com/tensorflow/tfjs-core/blob/0ed85bb92b99eb299e34efcabfd33575de9d5879/src/types.ts#L167)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

getOutputs
</blockquote></details>

+1 typo s/ouputs/outputs/

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1089#-:-LEu6UHH4g250aQyRbom:b-pofaf0)*

**Comment by caisq** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/types.ts, line 162 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/1089#-LEu808d-RSk-YMcWLfO:-LEu808e6D8TtDr0fKUW:b-222k6a) ([raw file](https://github.com/tensorflow/tfjs-core/blob/3b7c7d283b10bad374a862551becb44e06894f09/src/types.ts#L162)):*
> ```XML
>    * Return the array of input tensor info.
>    */
>   readonly inputs: TensorInfo[];
> ```

Ping, did you get a chance to look at the comments I made on the design doc? 

I think this shouldn't be readonly. If you make this readonly, it'll cause issue for tf.Model, because in tf.Model, the inputs and outputs can change.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1089)*

**Comment by caisq** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 2 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1089#-:-LEz9_YM0OJxf22M8O8j:b-jbsf8z)*

**Comment by pyu10055** [comment]
Review status: :shipit: complete! 2 of 1 LGTMs obtained

---

*[src/types.ts, line 162 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/1089#-LEu808d-RSk-YMcWLfO:-LEzBBKY1FX8MIa0mdnX:bd7nedk) ([raw file](https://github.com/tensorflow/tfjs-core/blob/3b7c7d283b10bad374a862551becb44e06894f09/src/types.ts#L162)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

Ping, did you get a chance to look at the comments I made on the design doc? 

I think this shouldn't be readonly. If you make this readonly, it'll cause issue for tf.Model, because in tf.Model, the inputs and outputs can change.
</blockquote></details>

as discussed offline, the interface readonly field only affects objects that cast to the interface not the tf.Model instances, means the inputs/outputs fields of tf.Model can still be mutatble.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1089)*

**Pull request merged**
