### PR TITLE
add support for StridedSlice

### PR DESCRIPTION
**Pull request by pyu10055**
implemented StridedSlice with beginMask/endMask support.

ellipsisMask, newMask, shrinkMask are not supported in this implementation.

fix https://github.com/tensorflow/tfjs/issues/242

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1026)

### CODE REVIEW

**Comment by nsthorat** [comment]
First pass through. Major comment is that the backend.ts should mirror the C API:

https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/python/ops/array_ops.py#L753

Once you fix this I will give this another pass. Thanks Ping, nice work!

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/kernels/backend.ts, line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFy36fB1qXIWghpTrq:-LCFy36gBrucgXACG5EE:b-o7cki3) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/kernels/backend.ts#L53)):*
> ```XML
> 
>   slice<T extends Tensor>(x: T, begin: number[], size: number[]): T;
>   stridedSlice<T extends Tensor>(
> ```

so this interface should mirror the TF C API so that we can bind to the TF backend:

https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/python/ops/array_ops.py#L753

---

*[src/kernels/backend_cpu.ts, line 163 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFzYda-4xFEgCoL-6o:-LCFzYda-4xFEgCoL-6p:btd3cno) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/kernels/backend_cpu.ts#L163)):*
> ```XML
>       const loc = buffer.indexToLoc(i);
> 
>       // Permute location.
> ```

remove this comment

---

*[src/kernels/webgl/strided_slice_gpu.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFzU6R6Mi9f5UL0rZA:-LCFzU6R6Mi9f5UL0rZB:b-pi9d9n) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/kernels/webgl/strided_slice_gpu.ts#L31)):*
> ```XML
>     this.rank = shape.length;
>     const dtype = getCoordsDataType(this.rank);
>     console.log(shape);
> ```

remove this

---

*[src/kernels/webgl/strided_slice_gpu.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFydPOEyjsMlhUT_VK:-LCFydPOEyjsMlhUT_VL:bv9oryi) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/kernels/webgl/strided_slice_gpu.ts#L47)):*
> ```XML
> 
>       void main() {
>         ${dtype} coords = getOutputCoords();
> ```

unindent

---

*[src/ops/strided_slice.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFy_qN3vNqLNeVE6TN:-LCFy_qN3vNqLNeVE6TO:bsauyqk) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L18)):*
> ```XML
>  */
> 
> import {tensor} from '..';
> ```

import this directly from tensor.ts

---

*[src/ops/strided_slice.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFz-Q-BRAV7XPmGxWX:-LCFz-Q-BRAV7XPmGxWY:bi716gq) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L47)):*
> ```XML
>    *
>    * @param x The tensor to stride slice.
>    * @param begin An int32 Tensor.
> ```

update these, they're not tensors

---

*[src/ops/strided_slice.ts, line 76 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCG-AAP0I9UJFQCGeoU:-LCG-AAP0I9UJFQCGeoV:b-fi7nnw) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L76)):*
> ```XML
>       let count = 0;
>       for (let start = startIndex[i];
>            !StridedSliceOps.loopCondition(start, endIndex[i], strides[i]);
> ```

this is a pretty trivial function, maybe just inline it?

---

*[src/ops/strided_slice.ts, line 83 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFyGEF5-BSf6kXkAVV:-LCFyGEF5-BSf6kXkAVW:b-onm7d9) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L83)):*
> ```XML
>     });
>     // TODO(piyu): Add grad function for strided slice.
>     const grad = (dy: T) => {
> ```

you should not define grad -- right now this will silently give the wrong result. if you pass nothing then we'll throw an error if you try to differentiate through this

---

*[src/ops/strided_slice.ts, line 88 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFzl1b7gcuuTrBBwi6:-LCFzl1b7gcuuTrBBwi7:bvaeo12) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L88)):*
> ```XML
>     return ENV.engine.runKernel(
>                size.some(axis => axis === 0) ?
>                    backend => tensor([], size) :
> ```

wait, this is going to return an empty tensor, is that right?

---

*[src/ops/strided_slice.ts, line 94 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFyP5M9pdM33U6Zqga:-LCFyP5M9pdM33U6Zqgb:b-nxdu5m) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L94)):*
> ```XML
>   }
> 
>   private static clamp(value: number, low: number, high: number) {
> ```

move these to floating functions not on the class

---

*[src/ops/strided_slice.ts, line 109 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFzzJlAcFpxuWP4Hce:-LCFzzJlAcFpxuWP4Hcf:b7yoww0) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L109)):*
> ```XML
> 
>     // beginMask override
>     if (beginMask & 1 << axis) {
> ```

this is pretty cryptic, can you explain this? Is there test

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-:-LCG-RE475AL99a1kblF:b-39aqym)*

**Comment by pyu10055** [comment]
thanks for the review, PTAL

---

Review status: 0 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[src/kernels/backend.ts, line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFy36fB1qXIWghpTrq:-LCGW7Hg8qOuDcyPVsjA:b-bv9u9i) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/kernels/backend.ts#L53)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

so this interface should mirror the TF C API so that we can bind to the TF backend:

https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/python/ops/array_ops.py#L753
</blockquote></details>

I added the params that we currently support to the backend.ts for stridedSlice, it also has some extra params that is derived by the strided_slice.ts. I assume node just need the params passed in, having extra would not be problematic.

---

*[src/kernels/backend_cpu.ts, line 163 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFzYda-4xFEgCoL-6o:-LCGWAm6B8jSgITErRxg:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/kernels/backend_cpu.ts#L163)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

remove this comment
</blockquote></details>

Done.

---

*[src/kernels/webgl/strided_slice_gpu.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFzU6R6Mi9f5UL0rZA:-LCGWGKvCg-pQpXdQ7uC:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/kernels/webgl/strided_slice_gpu.ts#L31)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

remove this
</blockquote></details>

Done.

---

*[src/kernels/webgl/strided_slice_gpu.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFydPOEyjsMlhUT_VK:-LCGWLDDBL-WVjfM97nS:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/kernels/webgl/strided_slice_gpu.ts#L47)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

unindent
</blockquote></details>

Done.

---

*[src/ops/strided_slice.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFy_qN3vNqLNeVE6TN:-LCGXdrYDq8REeQ8bj8q:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L18)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

import this directly from tensor.ts
</blockquote></details>

Done.

---

*[src/ops/strided_slice.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFz-Q-BRAV7XPmGxWX:-LCGXfCp-IJM7B_bjpak:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L47)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

update these, they're not tensors
</blockquote></details>

Done.

---

*[src/ops/strided_slice.ts, line 76 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCG-AAP0I9UJFQCGeoU:-LCGYA8661nQBjy60QWM:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L76)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

this is a pretty trivial function, maybe just inline it?
</blockquote></details>

Done.

---

*[src/ops/strided_slice.ts, line 83 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFyGEF5-BSf6kXkAVV:-LCGYB1-3Sw7HpJ_Tmzz:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L83)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

you should not define grad -- right now this will silently give the wrong result. if you pass nothing then we'll throw an error if you try to differentiate through this
</blockquote></details>

Done.

---

*[src/ops/strided_slice.ts, line 88 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFzl1b7gcuuTrBBwi6:-LCGYD2q2Ca9w0rRTATE:b-5ijvot) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L88)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

wait, this is going to return an empty tensor, is that right?
</blockquote></details>

yes, if any axis is 0, return an empty tensor.

---

*[src/ops/strided_slice.ts, line 94 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFyP5M9pdM33U6Zqga:-LCG_Ptx985czKWHz7ug:b-l7qcs) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L94)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

move these to floating functions not on the class
</blockquote></details>

Done. using the clamp function from util.ts

---

*[src/ops/strided_slice.ts, line 109 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFzzJlAcFpxuWP4Hce:-LCGYgcf-ajt59vcHeUK:by0bih0) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/ops/strided_slice.ts#L109)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

this is pretty cryptic, can you explain this? Is there test
</blockquote></details>

done and yes, there are test for using the beginMask and endMask

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-:-LCG_Kca8iUrAFXxRiyU:ba3eikz)*

**Comment by pyu10055** [comment]
make the backend API aligned with TF c, PTAL.

---

Review status: 0 of 8 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-:-LCVnwzc3inw1YIq0mW7:b-w0knqy)*

**Comment by nsthorat** [comment]
:lgtm_strong:

Really nice work Ping. People are going to thank you :D

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/kernels/backend.ts, line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-LCFy36fB1qXIWghpTrq:-LCZ43fv8BSh1g65tsZ-:b-vu0gal) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f144844536b447fdb6cdeca6271f3a7dd6ad9581/src/kernels/backend.ts#L53)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I added the params that we currently support to the backend.ts for stridedSlice, it also has some extra params that is derived by the strided_slice.ts. I assume node just need the params passed in, having extra would not be problematic.
</blockquote></details>

Yeah I think this is good!

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1026#-:-LCZ6smTEesp6p4GYDwi:bf1os8r)*

**Pull request merged**
