### PR TITLE
Ensure that dl.div() throws with mismatched types.

### PR DESCRIPTION
**Pull request by nkreeger**
Matches tf.div() execution:
https://www.tensorflow.org/api_docs/python/tf/div

Python docs day that float32 can be sent in, but testing this python code throws an exception (and complies to Op registration signature)

```
import tensorflow as tf

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    a = tf.constant([4, 4], dtype='int32')
    b = tf.constant([2, 2], dtype='float32')
    tf.div(a, b).eval()
```

Output:
```
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("Const_1:0", shape=(2,), dtype=float32)'
```

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/853)

### CODE REVIEW

**Comment by dsmilkov** [comment]
:lgtm_strong: Thank you!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/853#-:-L7airV3sQbay0SIdFI4:b-vn5y6t)*

**Comment by dsmilkov** [comment]
FYI: 1 test is failing that relied on div being non-strict with types. Otherwise this is good to go

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/ops/arithmetic_test.ts, line 172 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/853#-L9GvxLU3GBKf550WnHb:-L9GvxLU3GBKf550WnHc:bakdz3) ([raw file](https://github.com/tensorflow/tfjs-core/blob/dbe820320990af1dfd3da7d1df233b489b647ce1/src/ops/arithmetic_test.ts#L172)):*
> ```XML
>     const dy = dl.tensor1d([1, 19, 20]);
> 
>     const grads = dl.grads((a, b) => dl.div(a.cast('int32'), b));
> ```

optional: you can do `a.toInt()`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/853#-:-L9Gw4fk0hYGV-xKs6l0:b-jbsf8z)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/853#-:-L9H18OlAPbZhjJFDPQ3:b-jbsf8z)*

**Pull request merged**
