### PR TITLE
Issue Template: Adds initial issue template

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR adds initial issue template.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/915)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[ISSUE_TEMPLATE.md, line 5 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/915#-L8xB4e9BqBSz6S229WQ:-L8xB4e9BqBSz6S229WR:br73tj5) ([raw file](https://github.com/tensorflow/tfjs-core/blob/4add2abe8ce307ee4fb9b730e25d4d008bd49c65/ISSUE_TEMPLATE.md#L5)):*
> ```Markdown
> better fit.
> 
> #### TensorFlow.js version
> ```

We are trying to consolidate the use tensorflow/tfjs for tacking issues for both `core` and `layers`. We'll use labels to separate the `core` issues from `layers` issues. Having a template here is still useful to redirect our users to tensorflow/tfjs.

Maybe something like:

Since the launch of TensorFlow.js, we are using tensorflow/tfjs for keeping track of issues. Please file an issue on that repo instead: https://github.com/tensorflow/tfjs/issues/new

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/915)*

**Comment by ManrajGrover** [comment]
@dsmilkov Ah, wouldn't that make it a little difficult to manage, track and reference issues?

**Comment by dsmilkov** [comment]
Good point. Let's keep the issues here and not redirect people. I'll merge this as is (no changes needed)

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/915#-:-L8yBh9-4oRNVlxOieIJ:b-jbsf8z)*

**Pull request merged**
