### PR TITLE
Fix reference issue in free-packed-reshape-conv2D approach

### PR DESCRIPTION
**Pull request by astojilj**
This fix relates to tensorflow/tfjs#949 and fix committed in PR #1495.

xTexData.shape gets referenced from GPGPUBinary.inShapeInfos. Decrementing
row count, after batchMatMul->...->compileProgram leads to invalid row
count within the reference in GPGPUBinary.inShapeInfos. Proper way would be
to provide a copy to GPGPUBinary.inShapeInfos but that would affect
all the program compilation - so, provide a  copy, with even row cound,
when calling batchMatMul->...->compileProgram and after that, the original
xTexData.shape is restored.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1553)

### CODE REVIEW

**Comment by astojilj** [comment]
@annxingyuan 
PTAL
I wasn't able to create a test that would repproduce the issue, but was able to verify incorrect state using instrumentation code on deeplab model.

**Comment by annxingyuan** [comment]
Thanks @astojilj ! 

Can you explain why it's not possible to create a test case?

**Comment by astojilj** [comment]
> Thanks @astojilj !
> 
> Can you explain why it's not possible to create a test case?
@annxingyuan 

Not yet :) I'm able to reproduce it with other, invalid changes within backend_webgl.ts I use to  benchmark performance, but wasn't able to create such state from unit tests with original backend_webgl.ts. I'll continue trying to do it.

**Comment by astojilj** [comment]
Closing as merged to PR #1599

**Pull request closed without merging**
