### PR TITLE
[DEV] chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1039)

### CODE REVIEW

**Comment by dsmilkov** [comment]
:lgtm_strong: Thank you!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1039#-:-LCcLMoNBT-TQSEUWLRG:b-vn5y6t)*

**Comment by nsthorat** [comment]
Hi @DanielRuf it looks like this broke the build. Would you mind taking a look?

https://travis-ci.org/tensorflow/tfjs-core/jobs/379663743

Thanks!

**Comment by DanielRuf** [comment]
Not sure why this was merged at all.

bildschirmfoto 2018-05-16 um 17 07 57

Please revert so I can fix the unit tests and probably update the dependencies.

**Comment by DanielRuf** [comment]
I don't think that this is related to my changes:

> The command "if [ "$BROWSERSTACK_KEY" ]; then yarn test-travis; fi" exited with 1.

**Comment by nsthorat** [comment]
No worries. That line is a red herring.

I'm going to remove the check here since we always have the bstack key: https://github.com/tensorflow/tfjs-core/pull/1044

I think the issue is with this:

```
(node:3909) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ karma start --browsers='bs_firefox_mac,bs_chrome_mac' --singleRun
node[3930]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [node]
 2: 0x876c55 [node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [node]
 5: 0xacd2df [node]
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0xf0c4f28427d
```

**Pull request merged**
