### PR TITLE
Add inverse trig hyperbolic functions

### PR DESCRIPTION
**Pull request by jgartman**
This PR adds `tf.asinh`, `tf.acosh`, and `tf.atanh` to the API

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/927)

### CODE REVIEW

**Comment by nsthorat** [comment]
:lgtm_strong:

Really nice work, I don't have any comments!

---

Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/927#-:-L9gYdrE9F5dx7gAi2ox:be8l26g)*

**Comment by nsthorat** [comment]
Ah make sure you sync with master and then I can squash / merge this change.

**Comment by jgartman** [comment]
@nsthorat I misread your message and rebased on top of master instead of just merging.  Sorry if that means you have to look through all the changes again.

**Comment by nsthorat** [comment]
No worries, just looked through and it looks great.

Thanks for the contribution, I appreciate the attention to detail with test coverage!

**Comment by QuantumInformation** [comment]
Ah I just saw the  unary_op string builder for GLSL

**Comment by nsthorat** [comment]
@QuantumInformation, our WebGL programs are spliced together by JavaScript. We have some scaffolding set up so unary ops are really simple, you just write the body of the unary op function in GLSL and we take care of the rest.

Does that make sense?

**Comment by QuantumInformation** [comment]
Yes, I'm trying to get into contributing here, was wondering about this one, do I use a combination of the ops or just do it all in GLSL

https://github.com/tensorflow/tfjs/issues/157

**Comment by nsthorat** [comment]
Will respond over there.

**Pull request merged**
