### PR TITLE
Support tensors rank 5

### PR DESCRIPTION
**Pull request by zaidalyafeai**
Added tensors rank 5. This is still a work in progress. The shader_compiler.ts file needs to be further revised ... Many gpu operations needs to be changed like reverse, transpose, slice ...

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1022)

### CODE REVIEW

**Comment by zaidalyafeai** [comment]
Does anybody have time to review this? I am traveling in a few days and will not have time to work on the comments.

**Comment by dsmilkov** [comment]
@zaidalyafeai , this is a great start to adding 5D. Thank you for this change. Since you already modified `pad`, `reverse`, `transpose` and `tile` to work with 5D in this PR, you'll have to add tests for those ops as well. I only see 5d tests for `tile`. Let me know once you add those tests and then this will be ready to go.

I'm happy to also review future PRs that change other ops to work with 5D. Thank you!

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/ops/array_ops.ts, line 263 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1022#-LCMLI9V0M5YOzVE1ZDh:-LCMLI9V0M5YOzVE1ZDi:b-9pt9x7) ([raw file](https://github.com/tensorflow/tfjs-core/blob/bc9a267853ca0ba3d928c56af5aa93e50ecc0a50/src/ops/array_ops.ts#L263)):*
> ```XML
>    * ```js
>    * // Pass a flat array and specify a shape.
>    * tf.tensor4d([1, 2, 3, 4, 5, 6], [1, 2, 2, 2, 1]).print();
> ```

call tensor5d

---

*[src/ops/array_ops.ts, line 277 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1022#-LCMLVb2BSwFbB9o8w4T:-LCMLVb2BSwFbB9o8w4U:b-5zm1wa) ([raw file](https://github.com/tensorflow/tfjs-core/blob/bc9a267853ca0ba3d928c56af5aa93e50ecc0a50/src/ops/array_ops.ts#L277)):*
> ```XML
>       dtype: DataType = 'float32'): Tensor5D {
>     if (shape != null && shape.length !== 5) {
>       throw new Error('tensor5d() requires shape to have four numbers');
> ```

fix error message to say five numbers instead of four

---

*[src/ops/array_ops.ts, line 1008 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/1022#-LCMLwNEB4MepY5n1c1d:-LCMLwNEB4MepY5n1c1e:b-gfwzor) ([raw file](https://github.com/tensorflow/tfjs-core/blob/bc9a267853ca0ba3d928c56af5aa93e50ecc0a50/src/ops/array_ops.ts#L1008)):*
> ```XML
>       constantValue = 0): Tensor5D {
>     util.assert(
>         paddings.length === 4 && paddings[0].length === 2 &&
> ```

fix these checks to be for 5d (the current values are for the 4d case)

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1022#-:-LCMN79W1M-Ag5_qlC4G:b-t650wa)*

**Comment by zaidalyafeai** [comment]
@dsmilkov, I will not have the time to add unit tests for reverse, pad and transpose because I am getting ready to travel. Should I revert the changes I made to those operations ( they are minimal) ?

**Comment by dsmilkov** [comment]
No worries. Reverting those sounds good and then we can continue later with the follow up changes. Safe travels!

**Comment by nsthorat** [comment]
Let me know when this is ready to look at again.

**Comment by zaidalyafeai** [comment]
@nsthorat I already commited my final changes.

**Comment by nsthorat** [comment]
It's looking good! Would be good to add some unit tests for operations with 5D Tensors that aren't just construction, specifically for operations that operate on any rank (mean, unary ops like square, etc).

---

Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1022#-:-LC_FsE7DXqAOXxRWT46:b-kf56cq)*

**Comment by rodrigob** [comment]
> it is not clear to me what operations should I focus on.
why not start with `mean` and `square` and see from there ?

**Comment by zaidalyafeai** [comment]
Since transpose is necessary for https://github.com/tensorflow/tfjs/issues/161 I implemented it . Maybe we can merge this and support the other gpu operations once needed ?

**Comment by zaidalyafeai** [comment]
@nsthorat @dsmilkov I added unit tests for abs and relu to make sure 5D tensors work fine. Let me know if we need more...

**Comment by dsmilkov** [comment]
:lgtm_strong: Thank you!! And sorry for the wait

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1022#-:-LE0S08zELpdE-M1wavy:brnew8h)*

**Comment by dsmilkov** [comment]
One unrelated test fails - it's a known test tracked in https://github.com/tensorflow/tfjs/issues/377 which shouldn't block this PR.

**Comment by zaidalyafeai** [comment]
Awesome 😀 glad it worked.

**Comment by zaidalyafeai** [comment]
@dsmilkov, time to work on the remaining gpu operations ?

**Pull request merged**
