### PR TITLE
Fix code snippet in docs where indices should be int32

### PR DESCRIPTION
**Pull request by nbardy**
The example was returning an error due to invalid tensor type.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/989)

### CODE REVIEW

**Comment by dsmilkov** [comment]
One comment I just noticed tf.oneHot needs the same fix.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/ops/array_ops.ts, line 540 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/989#-LAtDBLz3UZbuzdjcNmx:-LAtDBM-1Zq0i2wnoxj3:bqergq4) ([raw file](https://github.com/tensorflow/tfjs-core/blob/5568b7d6f3b15dcfad21442d021968baae5b94d8/src/ops/array_ops.ts#L540)):*
> ```XML
>    *
>    * ```js
>    * tf.oneHot(tf.tensor1d([0, 1]), 3).print();
> ```

can you change it here too. oneHot requires indices to be int32?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/989#-:-LAtDGEXBBLkrQKfcuwv:btarpg3)*

**Comment by dsmilkov** [comment]
Hi @nbardy , can you change tf.oneHot in the documentation too?

**Comment by ManrajGrover** [comment]
@dsmilkov I can raise a separate PR for it if it's okay

**Comment by dsmilkov** [comment]
Thanks! Will merge this in!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/989#-:-LBaQOS33cElDc8e01fM:b-wkxjp9)*

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/989#-:-LBaQS8w57op1A-hauLe:b-jbsf8z)*

**Pull request merged**
