### PR TITLE
Pull Request Template: Makes adding tag a separate section

### PR DESCRIPTION
**Pull request by ManrajGrover**
#### Description

This PR makes adding tags to PR a separate section. Also, adds the description section and guidelines.

This PR makes use of this template which can be used for reference.

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1050)

### CODE REVIEW

**Comment by dsmilkov** [comment]
This is great. One q: I don't see anywhere on github that the md file needs to be all caps (I only see the optional subdirectory needs to be all caps): https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1050#-:-LDcFVM3CBB0B2fzE35y:bs04ihp)*

**Comment by ManrajGrover** [comment]
No specific reason for that. I had made it upper case to keep it aligned with `ISSUES_TEMPLATE` and other docs in the repository.

**Comment by dsmilkov** [comment]
Sounds good. Hopefully the upper-case works

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1050#-:-LDhfszf8Hns3piCK1yA:b-jbsf8z)*

**Pull request merged**
