### PR TITLE
Gradient for tf.gather

### PR DESCRIPTION
**Pull request by jgartman**
This PR implements the gradient for `tf.gather`. https://github.com/tensorflow/tfjs/issues/135

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/981)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Really nice work! Left a few comments but nothing major. Will LGTM after your reply and merge. Thanks Josh!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/ops/array_ops.ts, line 883 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LApAdbU9LF90blaxSDc:-LApAdbU9LF90blaxSDd:bcq75kr) ([raw file](https://github.com/tensorflow/tfjs-core/blob/20280e5747cf1a8fc6c406cec19d8c15cab8c3ea/src/ops/array_ops.ts#L883)):*
> ```XML
> 
>     util.assert(indices.dtype === 'int32', 'Indices must be of dtype `int32`');
>     const axes = parseAxisParam(axis, x.shape);
> ```

to avoid dealing with `axes[0]` you can overwrite `axis`:
`axis = parseAxisParam(axis, x.shape)[0]`

---

*[src/ops/array_ops.ts, line 886 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LApBH4ZCwnx1ppB96MK:-LApBH4ZCwnx1ppB96ML:b-2epmqq) ([raw file](https://github.com/tensorflow/tfjs-core/blob/20280e5747cf1a8fc6c406cec19d8c15cab8c3ea/src/ops/array_ops.ts#L886)):*
> ```XML
>     const grad = (dy: T) => {
>       const derX = () => {
>         return unsortedSegmentSum(dy, indices, x.shape[axes[0]], axes[0]);
> ```

since you already wrote this op and TF has it ([tf.unsorted_segment_sum](https://www.tensorflow.org/api_docs/python/tf/unsorted_segment_sum)), can you expose it to the public API and add docs?

---

*[src/ops/array_ops.ts, line 894 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LApBXg-BhY-fgDO1yVk:-LApBXg-BhY-fgDO1yVl:b-w0q0qj) ([raw file](https://github.com/tensorflow/tfjs-core/blob/20280e5747cf1a8fc6c406cec19d8c15cab8c3ea/src/ops/array_ops.ts#L894)):*
> ```XML
>     };
>     return ENV.engine.runKernel(
>         backend => backend.gather(x, indices, axes[0]), {x, indices}, grad);
> ```

to save memory, and since the gradient for indices is meaningless, remove `derIndices` and remove it from `{x, indices}` passed to `runKernel`. That is:
```
return ENV.engine.runKernel(
        backend => backend.gather(x, indices, axes[0]), {x}, grad);
```

---

*[src/ops/array_ops.ts, line 1295 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LApGnns-zc6Guz6nJPW:-LApGnns-zc6Guz6nJPX:b-2aahgz) ([raw file](https://github.com/tensorflow/tfjs-core/blob/20280e5747cf1a8fc6c406cec19d8c15cab8c3ea/src/ops/array_ops.ts#L1295)):*
> ```XML
>       segmentIds.dtype === 'int32', 'Segment Ids must be of dtype `int32`');
> 
>   const axes = parseAxisParam(axis, x.shape);
> ```

same here: `axis = parseAxisParam(axis, x.shape)[0]`

---

*[src/ops/array_ops.ts, line 1313 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LAp97S771Mys164t8rW:-LAp97S771Mys164t8rX:bfj0tan) ([raw file](https://github.com/tensorflow/tfjs-core/blob/20280e5747cf1a8fc6c406cec19d8c15cab8c3ea/src/ops/array_ops.ts#L1313)):*
> ```XML
>   const reshapedSegmentIds = ArrayOps.reshape(segmentIds, newShape);
>   for (let i = 0; i < numSegments; i++) {
>     const f = ArrayOps.fill(x.shape, i, 'int32');
> ```

If I understand correctly the shape, you can take advantage of the `equal` op to broadcast, so you can allocate a single scalar, and also call it `segmentId` instead of `f` for readability:
`const segmentId = scalar(i, 'int32');`

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-:-LApGzPO0Jo7qH6_lnia:b-pjdbc6)*

**Comment by jgartman** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/ops/array_ops.ts, line 883 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LApAdbU9LF90blaxSDc:-LAzkQOGAaWPWumeBovq:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/20280e5747cf1a8fc6c406cec19d8c15cab8c3ea/src/ops/array_ops.ts#L883)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

to avoid dealing with `axes[0]` you can overwrite `axis`:
`axis = parseAxisParam(axis, x.shape)[0]`
</blockquote></details>

Done.

---

*[src/ops/array_ops.ts, line 886 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LApBH4ZCwnx1ppB96MK:-LAzkUPXCqUIzE0WNA7S:b-dey3xd) ([raw file](https://github.com/tensorflow/tfjs-core/blob/20280e5747cf1a8fc6c406cec19d8c15cab8c3ea/src/ops/array_ops.ts#L886)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

since you already wrote this op and TF has it ([tf.unsorted_segment_sum](https://www.tensorflow.org/api_docs/python/tf/unsorted_segment_sum)), can you expose it to the public API and add docs?
</blockquote></details>

I exposed `unsortedSegmentSum`, I wasn't sure exactly where it should live in both the documentation and the ops files.  Currently it's under reduction ops in the documentation but in `arrays_ops.ts`.  Let me know if either of those should be changed.

---

*[src/ops/array_ops.ts, line 894 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LApBXg-BhY-fgDO1yVk:-LAzl2NJAKPn9k_1POol:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/20280e5747cf1a8fc6c406cec19d8c15cab8c3ea/src/ops/array_ops.ts#L894)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

to save memory, and since the gradient for indices is meaningless, remove `derIndices` and remove it from `{x, indices}` passed to `runKernel`. That is:
```
return ENV.engine.runKernel(
        backend => backend.gather(x, indices, axes[0]), {x}, grad);
```
</blockquote></details>

Done.

---

*[src/ops/array_ops.ts, line 1295 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LApGnns-zc6Guz6nJPW:-LAzl58qAJbGICafgI5R:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/20280e5747cf1a8fc6c406cec19d8c15cab8c3ea/src/ops/array_ops.ts#L1295)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

same here: `axis = parseAxisParam(axis, x.shape)[0]`
</blockquote></details>

Done.

---

*[src/ops/array_ops.ts, line 1313 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LAp97S771Mys164t8rW:-LAzl6PhD6mWogbJDgHc:b-b5f7ci) ([raw file](https://github.com/tensorflow/tfjs-core/blob/20280e5747cf1a8fc6c406cec19d8c15cab8c3ea/src/ops/array_ops.ts#L1313)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

If I understand correctly the shape, you can take advantage of the `equal` op to broadcast, so you can allocate a single scalar, and also call it `segmentId` instead of `f` for readability:
`const segmentId = scalar(i, 'int32');`
</blockquote></details>

Done, thanks for noticing that, I completely missed it.

---

*[src/ops/array_ops.ts, line 1293 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LAzlkT-7kgSrRW3b0bc:-LAzlkT-7kgSrRW3b0bd:b6nnmo9) ([raw file](https://github.com/tensorflow/tfjs-core/blob/9dfbf1fdd7a6f76dea12ec537cd922b19b6c6ff1/src/ops/array_ops.ts#L1293)):*
> ```XML
>           CompareOps.equal(segmentId, reshapedSegmentIds).asType('float32');
>       const sum = mask.mul(x).sum(axis);
>       res.push(sum);
> ```

Do I need to dispose of intermediate tensors like `mask` or do they get cleaned up automatically?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/981)*

**Comment by dsmilkov** [comment]
Thanks, and sorry for the delay. Couple small things left (see comments). Really nice work man

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/ops/array_ops.ts, line 886 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LApBH4ZCwnx1ppB96MK:-LBa9KcuENLrJKZh69AK:b-3xlv8p) ([raw file](https://github.com/tensorflow/tfjs-core/blob/20280e5747cf1a8fc6c406cec19d8c15cab8c3ea/src/ops/array_ops.ts#L886)):*
<details><summary><i>Previously, jgartman (Josh Gartman) wrote…</i></summary><blockquote>

I exposed `unsortedSegmentSum`, I wasn't sure exactly where it should live in both the documentation and the ops files.  Currently it's under reduction ops in the documentation but in `arrays_ops.ts`.  Let me know if either of those should be changed.
</blockquote></details>

Thanks! The subheading 'Reduction'` seems reasonable since it is a reduction operation. As for which file, we have `reduction_ops.ts`. Can you move it there?

---

*[src/ops/array_ops.ts, line 1249 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LBaAfyg5w3FFhxyiTSs:-LBaAfyg5w3FFhxyiTSt:b-gzndoi) ([raw file](https://github.com/tensorflow/tfjs-core/blob/9dfbf1fdd7a6f76dea12ec537cd922b19b6c6ff1/src/ops/array_ops.ts#L1249)):*
> ```XML
>    * ```js
>    * const x = tf.tensor1d([1, 2, 3, 4]);
>    * const indices = tf.tensor1d([1, 2, 0, 1]);
> ```

this snippet might error unless you explicitly say indices is of type `int32`

---

*[src/ops/array_ops.ts, line 1263 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LBaATIq9P8_mfryC7gw:-LBaATIq9P8_mfryC7gx:b-eestdu) ([raw file](https://github.com/tensorflow/tfjs-core/blob/9dfbf1fdd7a6f76dea12ec537cd922b19b6c6ff1/src/ops/array_ops.ts#L1263)):*
> ```XML
>    * calculated. Defaults to 0.
>    */
>   @doc({heading: 'Operations', subheading: 'Reduction'})
> ```

add `@operation` decorator right above @doc. This will wrap the whole method in a tidy which will dispose of intermediate textures.

---

*[src/ops/array_ops.ts, line 1293 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LAzlkT-7kgSrRW3b0bc:-LBaAaEu1Z_fRxxePl6h:bd4kgah) ([raw file](https://github.com/tensorflow/tfjs-core/blob/9dfbf1fdd7a6f76dea12ec537cd922b19b6c6ff1/src/ops/array_ops.ts#L1293)):*
<details><summary><i>Previously, jgartman (Josh Gartman) wrote…</i></summary><blockquote>

Do I need to dispose of intermediate tensors like `mask` or do they get cleaned up automatically?
</blockquote></details>

Great q. See my comment above. Add `@operation` decorator to this method

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-:-LBaArBrDrNTnaLTABYC:bomzg01)*

**Comment by jgartman** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/ops/array_ops.ts, line 886 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LApBH4ZCwnx1ppB96MK:-LBcunONBuY7IIaubx3o:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/20280e5747cf1a8fc6c406cec19d8c15cab8c3ea/src/ops/array_ops.ts#L886)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Thanks! The subheading 'Reduction'` seems reasonable since it is a reduction operation. As for which file, we have `reduction_ops.ts`. Can you move it there?
</blockquote></details>

Done.

---

*[src/ops/array_ops.ts, line 1249 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LBaAfyg5w3FFhxyiTSs:-LBcuq5562sxIltY-u3E:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/9dfbf1fdd7a6f76dea12ec537cd922b19b6c6ff1/src/ops/array_ops.ts#L1249)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

this snippet might error unless you explicitly say indices is of type `int32`
</blockquote></details>

Done.

---

*[src/ops/array_ops.ts, line 1263 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LBaATIq9P8_mfryC7gw:-LBcusHM0lev9zNcgnt7:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/9dfbf1fdd7a6f76dea12ec537cd922b19b6c6ff1/src/ops/array_ops.ts#L1263)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

add `@operation` decorator right above @doc. This will wrap the whole method in a tidy which will dispose of intermediate textures.
</blockquote></details>

Done.

---

*[src/ops/array_ops.ts, line 1293 at r2](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-LAzlkT-7kgSrRW3b0bc:-LBcutsm7mfVCCTaWuhi:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/9dfbf1fdd7a6f76dea12ec537cd922b19b6c6ff1/src/ops/array_ops.ts#L1293)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Great q. See my comment above. Add `@operation` decorator to this method
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/981)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Hey, Josh, sorry for the delay - I was travelling this past week! Thank you! 

---

Reviewed 3 of 6 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/981#-:-LCFmdQJ0yPtnSmdBPX5:b-bfjclx)*

**Pull request merged**
