### PR TITLE
Add tf.toPixels.

### PR DESCRIPTION
**Pull request by nsthorat**
Adds `tf.toPixels`, the inverse of `tf.fromPixels`.

Accepts a rank-2 tensor (grayscale) or a rank-3 tensor (colored). When using rank-3 tensors, accepts depth 1, 3, or 4. When depth 1, draws grayscale. When depth 3, draws RGB with alpha = 1. When depth 4, draws RGBA.

When using dtype = float32 assumes range of [0, 1] and when dtype = int32 assumes range of [0, 255]. This lets us call tf.toPixels(tf.fromPixels(x)), and cover the common case of generating floating point values 0 - 1.

This fixes https://github.com/tensorflow/tfjs/issues/103

This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/941)

### CODE REVIEW

**Comment by bileschi** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/ops/array_ops_test.ts, line 1156 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941#-L9ps-uT71ShCI5Wwrh2:-L9ps-uT71ShCI5Wwrh3:buac1de) ([raw file](https://github.com/tensorflow/tfjs-core/blob/519f1142100721a3a6bcb49746c17ebc5492f9d2/src/ops/array_ops_test.ts#L1156)):*
> ```
> use an alpha = 1 
> ```
Understandable, but there is no test where the alpha is anything but 255.  Is it possible to add a test that exercises the alpha, possibly without expectation on the color channel data?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941)*

**Comment by bileschi** [comment]
:lgtm_VERY_strong:  Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941#-:-L9psD1AEQCwy2jrs73U:b-yrcv88)*

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ops/array_ops.ts, line 580 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941#-L9pxYa36SztBp4HDd90:-L9pxYa36SztBp4HDd91:bc7n1ef) ([raw file](https://github.com/tensorflow/tfjs-core/blob/519f1142100721a3a6bcb49746c17ebc5492f9d2/src/ops/array_ops.ts#L580)):*
> ```XML
> 
>   /**
>    * Draws a `Tensor` shaped as an image to a canvas.
> ```

consider saying: Draws a `Tensor` of pixel values to a canvas.

---

*[src/ops/array_ops.ts, line 589 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941#-L9q56Hf9J53JQ8uJzut:-L9q56Hf9J53JQ8uJzuu:b2sn1kg) ([raw file](https://github.com/tensorflow/tfjs-core/blob/519f1142100721a3a6bcb49746c17ebc5492f9d2/src/ops/array_ops.ts#L589)):*
> ```XML
>    *
>    * @param img A rank-2 or rank-3 tensor. If rank-2, draws grayscale. If
>    *     rank-3, must have depth of 1, 3 or 4. When depth of 1, draw grayscale.
> ```

s/draw/draws/ at end of sentence

---

*[src/ops/array_ops.ts, line 608 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941#-L9q5RX-5R_H2HI-Fo1S:-L9q5RX-5R_H2HI-Fo1T:b-mk81rr) ([raw file](https://github.com/tensorflow/tfjs-core/blob/519f1142100721a3a6bcb49746c17ebc5492f9d2/src/ops/array_ops.ts#L608)):*
> ```XML
>       throw new Error(
>           `toPixels only supports depth of size ` +
>           `1, 3 or 4 but got ${img.shape[2]}`);
> ```

but got ${depth}

---

*[src/ops/array_ops.ts, line 618 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941#-L9q5YCRCg-yBf1hpZq7:-L9q5YCRCg-yBf1hpZq8:b5fql50) ([raw file](https://github.com/tensorflow/tfjs-core/blob/519f1142100721a3a6bcb49746c17ebc5492f9d2/src/ops/array_ops.ts#L618)):*
> ```XML
>     const multiplier = img.dtype === 'float32' ? 255 : 1;
>     for (let i = 0; i < height * width; ++i) {
>       let r, g, b, a;
> ```

if int32, throw an error if you come across a value that is not between 0-255. If float32, throw an error if a avlue is not between 0-1.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941#-:-L9q5kdK5z-jXQPDZqI2:b-jbsf8z)*

**Comment by tafsiri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/ops/array_ops.ts, line 596 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941#-L9q3pQy3yqRgqxHLmi1:-L9q3pQy3yqRgqxHLmi2:bzgoohs) ([raw file](https://github.com/tensorflow/tfjs-core/blob/519f1142100721a3a6bcb49746c17ebc5492f9d2/src/ops/array_ops.ts#L596)):*
> ```XML
>    */
>   @doc({heading: 'Visualization'})
>   static async toPixels(img: Tensor2D|Tensor3D, canvas: HTMLCanvasElement):
> ```

I know we want this to be symmetric with fromPixels, but should we just call this toCanvas? Also were we discussing having an option to just get the image data object back? a toCanvas method could use toPixels (that returns imagedata) if we wanted to go down that route.

---

*[src/ops/array_ops.ts, line 616 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941#-L9q3JvA59dk93N1qaG5:-L9q3JvA59dk93N1qaG6:b-2n2ffw) ([raw file](https://github.com/tensorflow/tfjs-core/blob/519f1142100721a3a6bcb49746c17ebc5492f9d2/src/ops/array_ops.ts#L616)):*
> ```XML
>     const imageData = new ImageData(width, height);
>     const data = await img.data();
>     const multiplier = img.dtype === 'float32' ? 255 : 1;
> ```

Should we assert the range is between 0 and 1 for a float32 array and throw an error? We could use tf max and min.

---

*[src/ops/array_ops.ts, line 637 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941#-L9q2j1L3zN2F0jP-WsU:-L9q2j1L3zN2F0jP-WsV:bz1p3gh) ([raw file](https://github.com/tensorflow/tfjs-core/blob/519f1142100721a3a6bcb49746c17ebc5492f9d2/src/ops/array_ops.ts#L637)):*
> ```XML
> 
>       const j = i * 4;
>       imageData.data[j + 0] = Math.floor(r);
> ```

I think the imageData.data assignment will do a round itself when a float is assigned. So we can drop the Math.floor call. Else i was going to ask why not use Math.round?

---

*[src/ops/array_ops_test.ts, line 1070 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941#-L9q4Hlb4nswpAjwGSFQ:-L9q4Hlb4nswpAjwGSFR:b-ezo3q2) ([raw file](https://github.com/tensorflow/tfjs-core/blob/519f1142100721a3a6bcb49746c17ebc5492f9d2/src/ops/array_ops_test.ts#L1070)):*
> ```XML
> 
>       expect(imgData.data).toEqual(new Uint8ClampedArray([
>         Math.floor(.1 * 255), Math.floor(.1 * 255), Math.floor(.1 * 255), 255,
> ```

If we use the imageData assignment, then i think this will need to change to Math.round. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/941)*

**Comment by carlthome** [comment]
Nice!

**Pull request merged**
