### PR TITLE
Bump version: 1.2.1 --> 1.2.2

### PR DESCRIPTION
**Pull request by caisq**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1804)

### CODE REVIEW

**Comment by nsthorat** [comment]
Hey Shanqing, waiting for 2 more PRs to land before doing this which I'm working on right now (so I can sync to g3). Is that okay?

Also 1.2.2 converter will hopefully wait for Daniel's string tensor change.

Also, can you use the yarn release script to do these?

**Comment by caisq** [comment]
@nsthorat OK. Let's wait for those. But we should do it swiftly, as nightly benchmark runs have stalled due to a missing op in tfjs-converter. Releasing a new version should fix it.

**Comment by nsthorat** [comment]
Last PR to wait for: https://github.com/tensorflow/tfjs-core/pull/1800

Once that's in can you try running the release script so that we make sure it's working for others?

**Comment by caisq** [comment]
#180 has been merged.

**Comment by nsthorat** [comment]
cool i’ll take care of the merge i need one more fix

**Comment by nsthorat** [comment]
Closing in favor of https://github.com/tensorflow/tfjs-core/pull/1806

**Pull request closed without merging**
