### PR TITLE
UnaryOps: Add dl.round

### PR DESCRIPTION
**Pull request by Lewuathe**
# Purpose

Add `dl.round`. As [tf.round](https://www.tensorflow.org/api_docs/python/tf/round) does, the algorithm is banker's rounding. 

see: https://github.com/PAIR-code/deeplearnjs/issues/894 and https://github.com/tensorflow/tfjs/issues/70

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/895)

### CODE REVIEW

**Comment by nsthorat** [comment]
:lgtm_strong:

Nice work here! small comments then I will merge

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/kernels/webgl/unaryop_gpu.ts, line 102 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/895#-L9VozlB8-7Zc1h8mhie:-L9VozlB8-7Zc1h8mhif:bmdjz95) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f860d1b63078887773fa40942664c715f7b76441/src/kernels/webgl/unaryop_gpu.ts#L102)):*
> ```XML
>   if ((x - base) < 0.5) {
>     return floor(x);
>   } else if ((x - base) > 0.5){
> ```

space before {

---

*[src/ops/unary_ops.ts, line 91 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/895#-L9Vot138k6PrVSkxcTf:-L9Vot138k6PrVSkxcTg:b-61cu30) ([raw file](https://github.com/tensorflow/tfjs-core/blob/f860d1b63078887773fa40942664c715f7b76441/src/ops/unary_ops.ts#L91)):*
> ```XML
>   /**
>    * Computes round of input `Tensor` element-wise: `round(x)`.
>    * It implements banker's rounding as tf.round does.
> ```

I would remove " as tf.round does" since it's a little confusing which TF. I would just say this op implements banker's rounding.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/895#-:-L9Vp12u9HBiWk6SlCAQ:bklhlh5)*

**Comment by Lewuathe** [comment]
@nsthorat Thank you for review! I update the patch accordingly.

**Comment by nsthorat** [comment]
There seems to be a trailing }); in unit tests, will merge after that (sorry for delay, when you're ready for another pass can you send me a comment?)

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/ops/unary_ops_test.ts, line 1774 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/895#-L9cGFtC-7wkwzLHP1oX:-L9cGFtC-7wkwzLHP1oY:b4u29vt) ([raw file](https://github.com/tensorflow/tfjs-core/blob/47b4606bc1b43667fc21531ab6508ee610f8437e/src/ops/unary_ops_test.ts#L1774)):*
> ```XML
>     expectArraysClose(gradients, [0, 0, 0, 0]);
>   });
> });  
> ```

something's off here, I see two "});"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-core/895#-:-L9cGNsoCrJn2DFZeswB:b-veop1g)*

**Comment by Lewuathe** [comment]
@nsthorat Thanks! I updated the patch!

**Pull request merged**
