### PR TITLE
Conv3d Implementation (complete, ready for review)

### PR DESCRIPTION
**Pull request by zboldyga**
#### Description
This is an implementation of conv3d, as discussed in:
https://github.com/tensorflow/tfjs/issues/470

This implementation has a functional CPU kernel that needs some additional unit tests and checking of a few more edge cases. 

The webGL kernel is incomplete. I will use this PR to communicate with people more knowledgeable around webGL and the 5d tensor implementation for guidance.

I also need to check my conv3d implementation against the recent changes to the conv2d implementation. For some reason the original conv2d routine was rewritten in the time since I started working on conv3d - I need to look at the prior PRs and see why. Since my conv3d implementation was based off of the old conv2d implementation, this may effect my conv3d implementation.

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1238)

### CODE REVIEW

**Comment by zboldyga** [comment]
The conv3d implementation has been updated to match mobilenet_v2 optimizations added to conv2d by @dsmilkov . conv3d backend_cpu implementation is complete, along with unit tests. This piece of the code can now be reviewed if you like. 

I still need to add unit tests for conv3DDerInput and conv3DDerFilter and ensure these are correct. I also still need to resolve the webGL implementation.

**Comment by mattgibb** [comment]
So exciting @zboldyga ! I'm just getting started with the codebase, but is there anything I can help with here?

**Comment by zboldyga** [comment]
@mattgibb I'm putting some finishing touches on things today and over the weekend. I'm going to try my best to figure out the webGL adaptation of conv3d, but if I can't sort it out in that timeframe I'd love some help!

**Comment by zboldyga** [comment]
@dsmilkov conv3d is complete / ready for review!

**Comment by kaczmarj** [comment]
@zboldyga - thanks for your effort on this. our group is planning to release a web-based 3D medical image segmentation tool using our trained tensorflow models, but the lack of 3D convolution support in tfjs has thwarted us.

**Comment by dsmilkov** [comment]
Hi @zboldyga, let me know when you take a pass after the comments, and I'm happy to merge after. This is a great addition to our library! Thanks!

**Comment by zboldyga** [comment]
@dsmilkov thanks so much for the detailed comments! At a glance everything you suggested makes sense and seems simple to implement. I will try my best to carve out time & have this completed within the next week.

**Comment by zboldyga** [comment]
@dsmilkov I believe I resolved all of the conflicts today. I pushed some more commits on the conv3d branch of my fork, but for some reason I'm not seeing those pulled-into this PR, and while they pass tests on my machine I haven't seen them in the CI test suite yet. Here's the link to my branch: https://github.com/zboldyga/tfjs-core/tree/conv3d . I can see one of the commits in this PR thread, but two additional ones aren't showing up...

**Comment by zboldyga** [comment]
@dsmilkov The changes were completed yesterday, and everything is testing OK locally. For some reason the CI tests haven't triggered on this PR yet, but the latest commit on the conv3d branch of my fork should be good to merge!

**Comment by zboldyga** [comment]
@dsmilkov Hey Daniel, just checking-in to see if you can take a look & merge this!

**Comment by mechaman** [comment]
@zboldyga @dsmilkov  Keen to have this merge go through to unblock my project! Thanks for getting this done @zboldyga !

**Comment by AKhazane** [comment]
Hey @zboldyga awesome work with this PR! My team is working on a medical imaging web application that requires 3D conv support.  @dsmilkov Thanks for taking the time to review this PR and looking forward to seeing it merged soon!

**Comment by zboldyga** [comment]
@dsmilkov 

:D :D :D Thanks! I'd love to pick up a big feature in TFJS to work on in Dec/Jan. If you run across anything meaty and want to include an outsider let me know!

**Comment by dsmilkov** [comment]
I'm so glad you are interested in helping more with TF.js - will keep you in mind. Ignore the CLA comment - the bot is confused since I pushed into your branch to resolve conflicts, but I can force merge.

**Pull request merged**
