### PR TITLE
Add serialization infrastructure to core

### PR DESCRIPTION
**Pull request by ericdnielsen**
This is half of a split PR across the two repos.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/997)

### CODE REVIEW

**Comment by ericdnielsen** [comment]
I know we've discussed exposing this as tf.registerSerializableClass from union.  But I think that's a third repo PR that can be decoupled from this pair.

**Comment by caisq** [comment]
Please take a look at the linter error:
https://travis-ci.org/tensorflow/tfjs-core/builds/371228940?utm_source=github_status&utm_medium=notification

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/index.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LAyVgm28Je1pdqwbNRm:-LAyVgm28Je1pdqwbNRn:b-x7qe2g) ([raw file](https://github.com/tensorflow/tfjs-core/blob/b7294f2316e35866942dd7a1642c85d171bea4b2/src/index.ts#L46)):*
> ```
> export * from './serialization';
> ```

Should you put them under a namespace like tf.serialization.* for cleanliness?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-:-LAyVojnAyfERkpKYovE:b-on010)*

**Comment by ericdnielsen** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/index.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LAyVgm28Je1pdqwbNRm:-LAyX5b30cYI6of9xA_A:b-dxhzui) ([raw file](https://github.com/tensorflow/tfjs-core/blob/b7294f2316e35866942dd7a1642c85d171bea4b2/src/index.ts#L46)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> export * from './serialization';
> ```

Should you put them under a namespace like tf.serialization.* for cleanliness?
</blockquote></details>

I thought that was handled at the union package level?

In any event, yes some, but I'm not sure all, should be namespaced.  Looking for some thoughts on that.  Just about every class in the Layers repo will need to import ConfigDict and SerializableMap.  The other ones are less common.  (Though I think once we proxy tf.registerSerializableClass -> SerializableMap.register(), we're only left with ConfigDict as a near universal import.

So I can maybe? see leaving the triplet of ConfigDict types in the root names space and moving the others?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/997)*

**Comment by ericdnielsen** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LAyeQhOA0-GFEXCbiJJ:-LAyeQhOA0-GFEXCbiJK:b-11s6gg) (no related file):*
Just added two files, suspect they'll be some breakages, but Daniel asked to see what it would look like to update a sample core Optimizer to be Serializable.  Since Optimizers share a common base class, we'll have to update them all at once.  I'd prefer to use the Optimizer purely for review purposes, then revert the changes to Optimizer and SGDOptimizer.  Migrate all of them in a single later PR.  Once we're happy with how it would potentially look.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/997)*

**Comment by ericdnielsen** [comment]
Review status: 0 of 10 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LAyeQhOA0-GFEXCbiJJ:-LBN8Gf9Asj16c4S4Luc:bvbk2tj) (no related file):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Overall this looks great. This barely adds anything to the bundle size and is a tiny change to the serializable classes.

Nice work.
</blockquote></details>

Added a few responses while I work through the rest, just to make sure I'm interpreting them right.

---

*[src/serialization.ts, line 96 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LBN4eUhAuQBxzYoFW7-:-LBN6idb8EUWo1u8LaGS:b1j272h) ([raw file](https://github.com/tensorflow/tfjs-core/blob/76015bb6c37ae66076c5b290a29b9c50c6b3d4d8/src/serialization.ts#L96)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

maybe we can just call this classNameMap since we may use this for non-pythonic serialization. let me know what you think.
</blockquote></details>

I think that rename works, once I add some jsDoc to outline the key of the map is expected to match the python name rather than the js name, if they differ.

---

*[src/optimizers/adadelta_optimizer.ts, line 106 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LBN3z0Y7klWcwiDMZtR:-LBN7rHND5FTxO1-XS9f:b-t47sc7) ([raw file](https://github.com/tensorflow/tfjs-core/blob/76015bb6c37ae66076c5b290a29b9c50c6b3d4d8/src/optimizers/adadelta_optimizer.ts#L106)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Instead of doing it this way, can we make all of the `number` fields separated from its Tensor version (admittedly my fault for making this inconsistency)? Eventually I'm going to add support for uploading numbers in place of Tensors so there won't be both.

Same in the other optimizers.
</blockquote></details>

That sounds good to me.  I'll adjust.  It looks like I should probably just add protected/private to the constructor args?  Don't think anything else would need to change (aside from simplifying my getConfigs)

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/997)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Looks good, worth adding a few unit tests.

---

Reviewed 1 of 2 files at r1, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/index.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LAyVgm28Je1pdqwbNRm:-LBNFSeE1etnJMPWwc76:b-qj4oix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/b7294f2316e35866942dd7a1642c85d171bea4b2/src/index.ts#L46)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

The union package just merges everything into a single package, it doesn't actually move symbols around. You should follow what "Second level exports" does below.
</blockquote></details>

+1 to moving this to a second-level export. See below:
```
// Second level exports.
export {environment, test_util, util, serialization};
```

---

*[src/serialization.ts, line 30 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LBO9DEX6By0x7Bu6HyG:-LBO9DEX6By0x7Bu6HyH:b-voh2lp) ([raw file](https://github.com/tensorflow/tfjs-core/blob/76015bb6c37ae66076c5b290a29b9c50c6b3d4d8/src/serialization.ts#L30)):*
> ```XML
>  * the pythonic version as that's the portable format.  If you need to
>  * python-ify a non-model level toConfig output, you'll need to use a
>  * to-be-written-helper doing the inverse of models::convertPythonicToTs.
> ```

what is the "::" symbol in this case, since we are not in C++?

---

*[src/optimizers/adadelta_optimizer.ts, line 106 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LBOAYnn3tWCRWWtRKCR:-LBOAYnn3tWCRWWtRKCS:bng30al) ([raw file](https://github.com/tensorflow/tfjs-core/blob/76015bb6c37ae66076c5b290a29b9c50c6b3d4d8/src/optimizers/adadelta_optimizer.ts#L106)):*
> ```XML
>   getConfig(): ConfigDict {
>     return {
>       learningRate: -1 * this.c.dataSync().values().next().value,
> ```

s/this.c.dataSync().values().next().value/this.c.get()/ here and elsewhere

---

*[src/optimizers/adam_optimizer.ts, line 132 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LBOC2bG9SMIKXaL6Ze9:-LBOC2bG9SMIKXaL6ZeA:b6883pt) ([raw file](https://github.com/tensorflow/tfjs-core/blob/76015bb6c37ae66076c5b290a29b9c50c6b3d4d8/src/optimizers/adam_optimizer.ts#L132)):*
> ```XML
>     return {
>       learningRate: this.learningRate,
>       beta1: this.beta1.dataSync().values().next().value,
> ```

same here: `this.beta1.get()`

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-:-LBOEao94wDL-57s4P77:bb3r4ed)*

**Comment by caisq** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[src/optimizers/adadelta_optimizer.ts, line 22 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LBRKkZ04D4Pnyd0Y873:-LBRKkZ04D4Pnyd0Y874:b-lb8v6q) ([raw file](https://github.com/tensorflow/tfjs-core/blob/76015bb6c37ae66076c5b290a29b9c50c6b3d4d8/src/optimizers/adadelta_optimizer.ts#L22)):*
> ```
>  SerializationMap
> ```

You plan to add the public `register` method in a later PR, right?

---

*[src/optimizers/adamax_optimizer.ts, line 134 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LBN4OFfE03U1zmz8bDa:-LBRL-wP4W_MN1vcxnhW:b32v57) ([raw file](https://github.com/tensorflow/tfjs-core/blob/76015bb6c37ae66076c5b290a29b9c50c6b3d4d8/src/optimizers/adamax_optimizer.ts#L134)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

overall this LGTM. can you add unit tests that check round trip serialization?
</blockquote></details>

+1

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/997)*

**Comment by nsthorat** [comment]
Review status: 2 of 17 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/index.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LAyVgm28Je1pdqwbNRm:-LBSKS9F7luYaps8w-vW:b61tbvl) ([raw file](https://github.com/tensorflow/tfjs-core/blob/b7294f2316e35866942dd7a1642c85d171bea4b2/src/index.ts#L46)):*
<details><summary><i>Previously, ericdnielsen wrote…</i></summary><blockquote>

when I try that it gets unhappy.  Can I grab one of you later to look at this in person?
</blockquote></details>

You have to import it first:

```
import * as serialization from './serialization';
...
export {environment, test_util, util, serialization};
```

---

*[src/optimizers/adadelta_optimizer.ts, line 106 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LBN3z0Y7klWcwiDMZtR:-LBSKgTB4iNcjpBN_dOc:bof0q8t) ([raw file](https://github.com/tensorflow/tfjs-core/blob/76015bb6c37ae66076c5b290a29b9c50c6b3d4d8/src/optimizers/adadelta_optimizer.ts#L106)):*
<details><summary><i>Previously, ericdnielsen wrote…</i></summary><blockquote>

That sounds good to me.  I'll adjust.  It looks like I should probably just add protected/private to the constructor args?  Don't think anything else would need to change (aside from simplifying my getConfigs)
</blockquote></details>

Yeah you just add those, however you will need to rename the tensor wrappers as well.

---

*[src/optimizers/adadelta_optimizer.ts, line 106 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LBOAYnn3tWCRWWtRKCR:-LBSL1zq3Rw87cVsh9Ew:b-g7sh2x) ([raw file](https://github.com/tensorflow/tfjs-core/blob/76015bb6c37ae66076c5b290a29b9c50c6b3d4d8/src/optimizers/adadelta_optimizer.ts#L106)):*
<details><summary><i>Previously, ericdnielsen wrote…</i></summary><blockquote>

So which do we want?  the c.get() that Daniel is listing, or introducing non-Tensor members?
</blockquote></details>

we chatted and prefer non-Tensor members (if for some reason you serialize every tick of training, this will cause serious perf issues. we also don't want to set the precedent that some tensors can be downloaded and serialized as part of the model).

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/997)*

**Comment by ericdnielsen** [comment]
Review status: 1 of 17 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/index.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LAyVgm28Je1pdqwbNRm:-LBW7_j1AVtcG4uugMCt:bum9f57) ([raw file](https://github.com/tensorflow/tfjs-core/blob/b7294f2316e35866942dd7a1642c85d171bea4b2/src/index.ts#L46)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

You have to import it first:

```
import * as serialization from './serialization';
...
export {environment, test_util, util, serialization};
```
</blockquote></details>

Done, but still need to confirm it doesn't make -layers use too awkward.

---

*[src/optimizers/adadelta_optimizer.ts, line 106 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LBN3z0Y7klWcwiDMZtR:-LBW7U_FB6eSg3-6nlZc:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/76015bb6c37ae66076c5b290a29b9c50c6b3d4d8/src/optimizers/adadelta_optimizer.ts#L106)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Yeah you just add those, however you will need to rename the tensor wrappers as well.
</blockquote></details>

Done.

---

*[src/optimizers/adadelta_optimizer.ts, line 106 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LBOAYnn3tWCRWWtRKCR:-LBW7V_703yw6U01ym9g:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/76015bb6c37ae66076c5b290a29b9c50c6b3d4d8/src/optimizers/adadelta_optimizer.ts#L106)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

we chatted and prefer non-Tensor members (if for some reason you serialize every tick of training, this will cause serious perf issues. we also don't want to set the precedent that some tensors can be downloaded and serialized as part of the model).
</blockquote></details>

Done.

---

*[src/optimizers/adam_optimizer.ts, line 132 at r3](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-LBOC2bG9SMIKXaL6Ze9:-LBW7XjeC5H58v2l0k8F:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-core/blob/76015bb6c37ae66076c5b290a29b9c50c6b3d4d8/src/optimizers/adam_optimizer.ts#L132)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

same here: `this.beta1.get()`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/997)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Good to submit. 

---

Reviewed 16 of 16 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/997#-:-LBaTIIj9I1K9IBCqp5m:b-6sv20x)*

**Pull request merged**
