### PR TITLE
Add fromPixels support for webworker

### PR DESCRIPTION
**Pull request by WenheLI**
This pr add fromPixels support for the Webworker environment.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1790)

### CODE REVIEW

**Comment by tafsiri** [comment]
Hi @WenheLI, after chatting with @nsthorat we figured that there are two pre-requisites we need to do before merging this PR.

1) Add more tests for tf.fromPixels for existing code paths. I made an [issue describing what we need](https://github.com/tensorflow/tfjs/issues/1665) to do here. 
2) Investigate running tests in a webworker ([link to issue](https://github.com/tensorflow/tfjs/issues/1666)). This will enable us to get a better picture of what is working and what isn't in a webworker. This is a bit more of an open ended exploration, so even putting notes/code snippets in the issue would be helpful.

Would you be willing to look into this? I'd say having 1) complete is definitely needed before merging this PR and 2) is helpful but based on what we find we can decide how to proceed.

**Comment by WenheLI** [comment]
Hi @tafsiri, sure things! I will look into them later!

**Comment by nsthorat** [comment]
Hi Wenhe,

Can you send a link to the failing CI? I can't seem to find it :)

**Comment by dsmilkov** [comment]
I synced with master so the error is gone. Yes, this is ready to merge! Thank you!

**Comment by anshumanvenkatesh** [comment]
Which version of tfjs will have this change?

**Comment by dsmilkov** [comment]
Should be available in the latest version `1.2.3`. Try it out and let us know otherwise. Note that you can't use htmlImageElement or video element in a webworker -- you have to pass ImageData or ImageData-like object `{data: Uint8Array}`.

**Pull request merged**
