### PR TITLE
Packed slice

### PR DESCRIPTION
**Pull request by astojilj**
Packed input sampling and packed output coordinate calculation
for arbitrary tensor rank. Slice tests verify 4-D, 5-D and 6-D.

Introduced WEBGL_PACK_ARRAY_OPERATIONS flag to configure usage
of packed SpaceToBatchND, BatchToSpaceND, slice, pad, transpose.

Generated shader userCode for e.g.

```
const a = tf.tensor2d([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [4, 3]);
const b = tf.slice2d(a, [1, 1], [3, 2]);
```

is

```
      uniform int start[2];
      void main() {
        ivec2 coords = getOutputCoords();
        ivec2 sourceLoc;
        sourceLoc = coords +
            ivec2(start[0],start[1]); 
        vec4 result = vec4(0.);
        
      result.x = getChannel(getSource(sourceLoc.x,sourceLoc.y), vec2(sourceLoc.x,sourceLoc.y));
      if (++coords.y < 2) {
        ++sourceLoc.y;
        result.y = getChannel(getSource(sourceLoc.x,sourceLoc.y), vec2(sourceLoc.x,sourceLoc.y));
        --sourceLoc.y;
      }
    
        
      --coords.y;
      if (++coords.x < 3) {
        ++sourceLoc.x;
        result.z = getChannel(getSource(sourceLoc.x,sourceLoc.y), vec2(sourceLoc.x,sourceLoc.y));
        if (++coords.y < 2) {
          ++sourceLoc.y;
          result.w = getChannel(getSource(sourceLoc.x,sourceLoc.y), vec2(sourceLoc.x,sourceLoc.y));
        }
      }
    
        setOutput(result);
      }
```

PERF

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-core/1497)

### CODE REVIEW

**Comment by astojilj** [comment]
@annxingyuan 
PTAL.
This PR is a split packed slice from [PR#1448](https://github.com/tensorflow/tfjs-core/pull/1448#issuecomment-447135078).

**Comment by annxingyuan** [comment]
@astojilj 

Hey - would also be great to see the compiled shader output for this PR - could you post an example for the following computation:

```
const a = tf.tensor2d([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [4, 3]);
const b = tf.slice2d(a, [1, 1], [3, 2]);
```

Thanks!

**Comment by astojilj** [comment]
@annxingyuan, compiled shader's userCode added to description.

**Comment by astojilj** [comment]
@annxingyuan
For the reference, adding a link to benchmark provided to PR #1504.

> With WEBGL_PACK and WEBGL_PACK_ARRAY_OPERATIONS set to true, inference takes ~125ms.
> With WEBGL_PACK set to true WEBGL_PACK_ARRAY_OPERATIONS set to false, inference takes ~150ms.

**Comment by annxingyuan** [comment]
Thanks @astojilj :)

**Pull request merged**
